### ISSUE TITLE
kinesisvideo  empty list  invoking Session().get_available_regions

### ISSUE THREAD

**Issue by giuliocalzolari** [boto/botocore#1378] opened 2018-02-07 16:37 UTC
invoking Session().get_available_regions it returns an empty list

```
>>> from boto3.session import Session
>>> Session().get_available_regions("kinesisvideo")
[]
>>> Session().get_available_regions("kinesis")
[u'ap-northeast-1', u'ap-northeast-2', u'ap-south-1', u'ap-southeast-1', u'ap-southeast-2', u'ca-central-1', u'eu-central-1', u'eu-west-1', u'eu-west-2', u'eu-west-3', u'sa-east-1', u'us-east-1', u'us-east-2', u'us-west-1', u'us-west-2']
```

expected results is:
`[u'ap-northeast-1', u'eu-central-1', u'eu-west-1', u'us-west-2', u'us-west-1']`

**Comment by kyleknap** [comment] 2018-02-09 20:17
Yep I can confirm. Those are also the expected regions as [documented](https://docs.aws.amazon.com/general/latest/gr/rande.html#akv_region). We will need to update the `endpoints.json` file. Marking as bug.

**Comment by JordonPhillips** [comment] 2018-02-20 18:17
This has since been fixed

**Closed by JordonPhillips** 2018-02-20 18:17 UTC
Labels: bug
