### ISSUE TITLE
Can't use custom region for custom s3

### ISSUE THREAD

**Issue by imamatory** [boto/botocore#2909] opened 2023-04-17 13:53 UTC
### Describe the bug

My project uses S3 region name in the format `xx_myregionname`. So using botocore I got an exception `botocore.exceptions.InvalidRegionError: Provided region_name 'xx_myregionname' doesn't match a supported format`.
I investigated that it happens because of the underscore in the region name. But I can't change the production configuration according to this library. This is weird behavior because the region name is taken from the session and not from my code.

### Expected Behavior

Validation of region name passes for the region of `xx_regionsname` format. At least when the region name came from the session.

### Current Behavior

Exception raises
```
.../lib/python3.9/site-packages/botocore/utils.py", line 1264, in validate_region_name
    raise InvalidRegionError(region_name=region_name)
botocore.exceptions.InvalidRegionError: Provided region_name 'zg_publicru' doesn't match a supported format.
```

### Reproduction Steps

1. Setup s3 bucket with region `xx_myregion`.
2. Try to upload a file to it with botocore.

### Possible Solution

Skip region name validation if it came from the session.

### Additional Information/Context

I use `django-storages` which uses `boto3` which uses `botocore`.

### SDK version used

1.26.7

### Environment details (OS name and version, etc.)

linux, mac os

**Comment by tim-finnigan** [comment] 2023-04-18 17:36
Hi @imamatory thanks for reaching out. [Here in the code](https://github.com/boto/botocore/blob/892c5bc73606ec02a6eff2522da1decff88d1c48/botocore/utils.py#L1265-L1272) is where that error is referenced. You can see the regular expression used to validate the region. For a list of valid region codes you can refer to this page: https://docs.aws.amazon.com/general/latest/gr/rande.html. In this case the region validation function appears to be working as intended. For issues like this one which involve third-party software, we recommend reaching out to directly to the vendors for support. If you have any other questions please let us know.

**Comment by imamatory** [comment] 2023-04-18 19:21
Hi [tim-finnigan](https://github.com/tim-finnigan)! Thanks for your reply. I am using an old version of Minio as S3 backend. It was configured years ago and there is no option to change it. 
Your point is fair but could please make it clear to me why the library code on the client side should validate the server setting?

**Comment by tim-finnigan** [comment] 2023-04-18 19:41
Hi, thanks for following up. Here is the PR where that function was added a few years ago: https://github.com/boto/botocore/pull/2127

As noted there:
>This PR will add some basic validation to the region_name parameter used to create new Session and BaseClient objects. **The goal is to avoid accidentally setting up clients that will either never route, or lead to unexpected request routing.** The change here will bubble up to boto3 in clients and resources, as well as the AWS CLI.

That PR was merged in 2020 and I wasn't able to find any other issues related to this one. Updating your version of Minio may resolve this issue, if not then you could open an issue in their repository: https://github.com/minio/minio/issues. I'm going to close this issue as it appears due to outdated third-party software, but if there's any problem directly related to boto3/botocore then we can revisit this and investigate it further.

**Closed by tim-finnigan** 2023-04-18 19:41 UTC
Labels: closing-soon, configuration
