### ISSUE TITLE
Botocore pagination params inconsistent

### ISSUE THREAD

**Issue by kyleknap** [boto/botocore#546] opened 2015-06-01 21:35 UTC
In the pagination interface, there are a few extra parameters related to pagination that are snake cased (``max_items``, ``page_size``, ``starting_token``). These are different than the camel casing of the parameters that are actually sent in the request. So you would get something like this (using ``s3.list_objects``):
```
paginator.paginate(Bucket='mybucket', page_size=1)
```

Ideally we would want to change the pagiantion related parameters to camel case as well (``MaxItems``, ``PageSize``, ``StartingToken``) for the sake of consistency. So the above pagination call would instead be:
```
paginator.paginate(Bucket='mybucket', PageSize=1)
```

Let me know what you think.

**Comment by kyleknap** [comment] 2015-06-01 21:39
If we want to avoid breaking changes, we can accept both snake cased and camel cased version of the parameters, but only document the camel cased version of the parameters.

**Comment by jamesls** [comment] 2015-06-01 21:49
One of the issues we've run into (in the CLI) is that sometimes our additional pagination args shadow an argument used by the service.  Sometimes they actually have a MaxItems argument.

In the CLI, I think we were getting away with this because there was a MaxItems vs. max_items so there was no collision.  I think with this approach we may see some collisions and have some unexpected behavior.

Just to throw another idea out there, what if we consolidate this into a single argument that's less likely to shadow a built in arg?  For example:

```
paginator.paginate(Bucket='mybucket', PaginationConfig={'PageSize': 100, 'MaxItems': 100})
```

**Comment by kyleknap** [comment] 2015-06-01 21:55
Good point. That sounds good with me.

**Comment by jamesls** [comment] 2015-06-05 19:23
Closing, fixed in https://github.com/boto/botocore/pull/547

**Closed by jamesls** 2015-06-05 19:23 UTC
Labels: breaking change, enhancement
