### ISSUE TITLE
ImportError: cannot import name 'is_s3express_bucket' from 'botocore.utils'

### ISSUE THREAD

**Issue by MostafaHosseinian** [boto/botocore#3083] opened 2023-11-29 15:17 UTC
### Describe the issue

In aws sagemaker, I used to install 'sagemaker==2.183.0', 'xgboost==1.5.1', 'statsmodels=0.13.5', and 'fasttreeshap==0.1.6' to launch a post processing job for my ML model. As of today, I've faced an import issue regarding botocore as follows. I wonder if you could help me out.
FYI, I tried to downgrade botocore to `1.32.5`, as before but the import error is still there.

ImportError: cannot import name 'is_s3express_bucket' from 'botocore.utils' (/miniconda3/lib/python3.7/site-packages/botocore/utils.py)

### Links

-

**Comment by nateprewitt** [comment] 2023-11-29 15:43
Hi @MostafaHosseinian, it looks like this is a duplicate of #3082. We'll track resolution of this issue there. If you don't mind confirming if you're on Lambda in that ticket, it will be helpful. Thanks!

**Closed by nateprewitt** 2023-11-29 15:43 UTC
Labels: documentation, needs-triage

**Comment by vhosakot** [comment] 2024-05-17 15:37
saw same error on mac when using `aws eks update-kubeconfig ...` cli, and below steps fixed it for me on mac:

```
$ aws eks update-kubeconfig --name <AWS EKS cluster name> --region <AWS region>
Traceback (most recent call last):
  File "/usr/local/bin/aws", line 27, in <module>
    sys.exit(main())
  File "/usr/local/bin/aws", line 23, in main
    return awscli.clidriver.main()
  File "/Users/vhosakot/Library/Python/3.9/lib/python/site-packages/awscli/clidriver.py", line 69, in main
    driver = create_clidriver()
  File "/Users/vhosakot/Library/Python/3.9/lib/python/site-packages/awscli/clidriver.py", line 78, in create_clidriver
    load_plugins(session.full_config.get('plugins', {}),
  File "/Users/vhosakot/Library/Python/3.9/lib/python/site-packages/awscli/plugin.py", line 44, in load_plugins
    modules = _import_plugins(plugin_mapping)
  File "/Users/vhosakot/Library/Python/3.9/lib/python/site-packages/awscli/plugin.py", line 61, in _import_plugins
    module = __import__(path, fromlist=[module])
  File "/Users/vhosakot/Library/Python/3.9/lib/python/site-packages/awscli/handlers.py", line 78, in <module>
    from awscli.customizations.s3.s3 import s3_plugin_initialize
  File "/Users/vhosakot/Library/Python/3.9/lib/python/site-packages/awscli/customizations/s3/s3.py", line 15, in <module>
    from awscli.customizations.s3.subcommands import ListCommand, WebsiteCommand, \
  File "/Users/vhosakot/Library/Python/3.9/lib/python/site-packages/awscli/customizations/s3/subcommands.py", line 18, in <module>
    from botocore.utils import is_s3express_bucket, ensure_boolean
ImportError: cannot import name 'is_s3express_bucket' from 'botocore.utils' (/Users/vhosakot/Library/Python/3.9/lib/python/site-packages/botocore/utils.py)

# saw above error with below versions
$ pip3 list | grep 'aws\|boto\|s3'                               
awscli                     1.32.80
boto3                      1.28.38
botocore                   1.31.85
s3transfer                 0.6.2
```

below steps fixed it for me:

```
pip3 uninstall -y awscli boto3 botocore s3transfer
pip3 install awscli

# below command worked for me
aws eks update-kubeconfig --name <AWS EKS cluster name> --region <AWS region>
```

**Comment by muhammedbasilsk** [comment] 2025-04-08 04:44
@vhosakot thanks
This worked.

```SHELL
pip3 uninstall -y awscli boto3 botocore s3transfer
pip3 install awscli
```
