### ISSUE TITLE
Lambda Boto3 client - Connection Aborted. RemoteDisconnected

### ISSUE THREAD

**Issue by sagar-86** [boto/botocore#2787] opened 2022-10-21 19:26 UTC
### Describe the bug

My lambda runtime is close to 4 minutes and the lambda invokes fine and ends without any issues when observed in AWS console, but when invoked through boto3 in a python script, it errors out at exact 60s. 

Same behavior and error when using `awscli`
```
Python 3.10.8 (main, Oct 13 2022, 10:17:43) [Clang 14.0.0 (clang-1400.0.29.102)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import boto3
>>> import botocore
>>> botocore.__version__
'1.27.92'
>>> boto3.__version__
'1.24.92'
```

### Expected Behavior

Expected the boto3 client to wait until the invocation has finished and proceed with the rest of the script

### Current Behavior

When invoking a lambda synchronously using `boto3` lambda client, getting below error at exact 60s. 

Function snippet -

```
session = boto3.Session(
    profile_name="ZZZZZZZ",
    region_name="us-east-1",
)
config = botocore.config.Config(
    read_timeout=900,
    connect_timeout=900,
    retries={"max_attempts": 0}
)
lambda_client = session.client("lambda", config=config)
lambda_parent_arn = "arn:aws:lambda:us-east-1:XXXXXXXXXXXX:function:YYYYYYYYYYYYYYYYYYYYY"
invoke_lambda_parameters = {
    "lambda_client": lambda_client,
    "lambda_parent_arn": lambda_parent_arn,
}
def _invoke_lambda(lambda_client,lambda_parent_arn: str,temp: str):
  response = lambda_client.invoke(
      FunctionName=lambda_parent_arn,
      InvocationType="RequestResponse",
      Payload=json.dumps({"source_tab": f"{temp}"}),
      LogType="Tail"
  )

temp_tables = []
for table in "psape","psapea":
    temp_tables.append(f"elfrd_work.elfrd_{table}_stage_temp_12")

for temp in temp_tables:
    invoke_lambda_parameters["temp"] = temp
    _invoke_lambda(**invoke_lambda_parameters)
```

Error Log - 

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/botocore/httpsession.py", line 455, in send
    urllib_response = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 525, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.10/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sagsrini/Documents/NSC/EDM-ELFRD/deploy/database/historical-load/historical-load-test.py", line 97, in <module>
    main()
  File "/Users/sagsrini/Documents/NSC/EDM-ELFRD/deploy/database/historical-load/historical-load-test.py", line 53, in main
    _invoke_lambda(**invoke_lambda_parameters)
  File "/Users/sagsrini/Documents/NSC/EDM-ELFRD/deploy/database/historical-load/historical-load-test.py", line 74, in _invoke_lambda
    response = lambda_client.invoke(
  File "/usr/local/lib/python3.10/site-packages/botocore/client.py", line 514, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.10/site-packages/botocore/client.py", line 921, in _make_api_call
    http, parsed_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/botocore/client.py", line 944, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/usr/local/lib/python3.10/site-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/lib/python3.10/site-packages/botocore/endpoint.py", line 202, in _send_request
    while self._needs_retry(
  File "/usr/local/lib/python3.10/site-packages/botocore/endpoint.py", line 354, in _needs_retry
    responses = self._event_emitter.emit(
  File "/usr/local/lib/python3.10/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python3.10/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/botocore/retryhandler.py", line 207, in __call__
    if self._checker(**checker_kwargs):
  File "/usr/local/lib/python3.10/site-packages/botocore/retryhandler.py", line 284, in __call__
    should_retry = self._should_retry(
  File "/usr/local/lib/python3.10/site-packages/botocore/retryhandler.py", line 320, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/usr/local/lib/python3.10/site-packages/botocore/retryhandler.py", line 363, in __call__
    checker_response = checker(
  File "/usr/local/lib/python3.10/site-packages/botocore/retryhandler.py", line 247, in __call__
    return self._check_caught_exception(
  File "/usr/local/lib/python3.10/site-packages/botocore/retryhandler.py", line 416, in _check_caught_exception
    raise caught_exception
  File "/usr/local/lib/python3.10/site-packages/botocore/endpoint.py", line 281, in _do_get_response
    http_response = self._send(request)
  File "/usr/local/lib/python3.10/site-packages/botocore/endpoint.py", line 377, in _send
    return self.http_session.send(request)
  File "/usr/local/lib/python3.10/site-packages/botocore/httpsession.py", line 494, in send
    raise ConnectionClosedError(
botocore.exceptions.ConnectionClosedError: Connection was closed before we received a valid response from endpoint URL: "https://lambda.us-east-1.amazonaws.com/2015-03-31/functions/arn%3Aaws%3Alambda%3Aus-east-1%3AXXXXXXXXXXXX%3Afunction%3AYYYYYYYYYYYYYYYYYYYYY/invocations".
```

### Reproduction Steps

1. Create a simple python 3.9 function in Lambda to wait for more than 60s
2. Invoke the lambda **synchronously** with `awscli` or with a script utilizing `boto3` SDK

### SDK version used

Boto3 = 1.24.92, Botocore = 1.27.92

### Environment details (OS name and version, etc.)

OS = macOS Monterey v12.6, Python = 3.10.8

**Comment by tim-finnigan** [comment] 2022-10-24 23:50
Hi @sagar-86 thanks for reaching out. Is this issue consistently reproducible or could it have been due to a network error? [This article](https://aws.amazon.com/premiumsupport/knowledge-center/lambda-function-retry-timeout-sdk/) on troubleshooting Lambda timeouts may help although it looks like you're already using a similar configuration as shown there. But you might consider trying the exact example they provided. Otherwise you could try enabling `tcp_keepalive` - that seems to address the timeout issue as mentioned here: https://github.com/boto/boto3/issues/2510#issuecomment-1163825488.

**Comment by sagar-86** [comment] 2022-10-26 16:24
I can reproduce this issue all day. Surprisingly this is happening at my customer's corporate laptop as well. Made sure I am not connected to VPN and that I am using latest botocore version. I even tried with `tcp_keepalive=True` Config option but I am getting same error as before at 60s. Even tried a packet capture and not seeing anything out of the ordinary.

**Comment by sagar-86** [comment] 2022-10-27 06:29
Stumbled upon https://github.com/aws/aws-cli/issues/5783 and tried changing the OS TCP limits as mentioned by @kdaily  - 
```
net.inet.tcp.keepidle: 20000
net.inet.tcp.keepintvl: 20000
net.inet.tcp.keepinit: 20000
net.inet.tcp.keepcnt: 8
net.inet.tcp.always_keepalive: 1
```

Still seeing same error as before.

**Comment by tim-finnigan** [comment] 2022-10-28 19:46
Hi @sagar-86 my colleague let me know that this was discussed internally and it was found that a VPN was causing the issue. Since the cause was found I will go ahead and close this issue. If there are any other details you want to add here please let us know. Thanks!

**Closed by tim-finnigan** 2022-10-28 19:46 UTC
Labels: bug, response-requested

**Comment by sagar-86** [comment] 2022-10-28 19:55
Thanks @tim-finnigan. Yes it was a VPN software which I had no clue was installed. Not connected, but just installed and uninstallation fixed the issue.
