### ISSUE TITLE
Started getting BadStatusLine

### ISSUE THREAD

**Issue by Jc2k** [boto/botocore#470] opened 2015-02-25 16:50 UTC
Happens on multiple API calls, but not repeatably. I haven't found a repeatable way to make it happen. Trying again immediately with same arguments it has so far always worked. Seen on multiple computers, on multiple networks. Always has this bit of the traceback in common:

```
 File "botocore/client.py", line 315, in _api_call
   operation_model, request_dict)
 File "botocore/endpoint.py", line 110, in make_request
   return self._send_request(request_dict, operation_model)
 File "botocore/endpoint.py", line 156, in _send_request
   success_response, exception):
 File "botocore/endpoint.py", line 205, in _needs_retry
   caught_exception=caught_exception)
 File "botocore/hooks.py", line 226, in emit
   return self._emit(event_name, kwargs)
 File "botocore/hooks.py", line 209, in _emit
   response = handler(**kwargs)
 File "botocore/retryhandler.py", line 180, in __call__
   if self._checker(attempts, response, caught_exception):
 File "botocore/retryhandler.py", line 247, in __call__
   caught_exception)
 File "botocore/retryhandler.py", line 262, in _should_retry
   return self._checker(attempt_number, response, caught_exception)
 File "botocore/retryhandler.py", line 310, in __call__
   caught_exception)
 File "botocore/retryhandler.py", line 219, in __call__
   return self._check_caught_exception(attempt_number, caught_exception)
 File "botocore/retryhandler.py", line 352, in _check_caught_exception
   raise caught_exception
botocore.vendored.requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))
```

I've definitely seen it using DescribeNetworkInterfaces and with one of the auto scaling API's so happens with multiple endpoints.

Given it's random nature i'm at a bit of a loss of what information I can capture to help track it down. Any ideas?

**Comment by kyleknap** [comment] 2015-02-25 17:36
How often does this happen?

This error is being generated from botocore's underlying http library, requests, which is related to the status code not being understandable by the library. I looked around for related issues and it seems that for most of the times that someone ran into this issue a proxy was involved. Could you describe the various environments/systems that you have tried it on?

Here is a stackoverflow issue that I found that describes the issue as well: http://stackoverflow.com/questions/18478013/python-requests-exceptions-connectionerror-max-retries-exceeded-witth-url. It seems that if you are using a proxy, it would not hurt to try to use a debugger or sniffer to figure out was being received.

**Comment by Jc2k** [comment] 2015-02-25 21:29
No explicit use of proxies on my end, and to the best of my knowledge no transparent proxies either. This is running from an FTTC fibre broadband connection provided by a good ISP - unfiltered, unshaped, uncapped with a static IP. There is NAT, however. I've also heard that it's been hit on another ISP as well, but I don't have any details about them.

The script I am running is for tearing down and rebuilding moderately sized environments using a bunch of different AWS services. Especially when setting up the Network ACL's it generates quite a few API calls (I can see it giving the retry logic a fairly good workout!).

I have done 2 tear downs and 2 rebuilds and seen it twice. But for different API calls on different endpoints, and other people have had it on yet other API calls.

All the failures have happened on Ubuntu. I'm seeing them on Trusty (the current LTS release), and i'm also getting reports of it happening on Precise.

The one thing that popped into my head is that gevent might have been inherited from another part of the project.

I'll modify my script to drop into pdb and see if I can get some more useful info.

**Comment by Jc2k** [comment] 2015-02-26 09:03
Still happens after disabling gevent. Hasn't yet happened when i've had a debugger on it.

**Comment by Jc2k** [comment] 2015-03-04 10:37
Seemed to start happening less frequently, but has returned. Have tried from a different line / IP. Same ISP, but different network setup (in particular, different router - so completely different NAT implementation).

Caught the ConnectionError in pdb, looks like the response is actually just an empty string. The comment in httplib says "Presumably the server closed the connection before sending a valid response".

**Comment by Jc2k** [comment] 2015-03-04 10:39
Is there something I can add to the retry json to get retrying in this case (at least for actions that are only list/get/describe type actions)?

**Comment by jamesls** [comment] 2015-03-04 18:40
@Jc2k What are the operations that cause the error to occur most frequently?  From the original post it sounds like `DescribeNetworkInterfaces`?  I'd like to track down exactly what's going on here.

Given this is a ConnectionError, it's actually already being retried.  The traceback shows the retryhandler is propogating the exception because the number of retries have been exhausted.

If you have a code snippet I can run in a loop to try and repro these issues that would be really helpful.

**Comment by Jc2k** [comment] 2015-03-04 20:45
I've only seen it once with ``DescribeNetworkInterfaces``. I actually only need to use ``DescribeNetworkInterfaces`` because there is no ``terminating`` status on ELB - it seems to just disappear from the API immediately even though it is still attached to the subnet. So if I want to delete an ELB and then delete the subnet it is in I end up looking in the list of network interfaces for a subnet with a description of "ELB balancer" and wait for it to go away before deleting the subnet :(

The code for that is just:

            interfaces = client.describe_network_interfaces(
                Filters=[
                    {"Name": "vpc-id", "Values": [vpc_id]},
                    {"Name": "subnet-id", "Values": [subnet_id]},
                ]
            )

(I realise that i don't need to specify vpc-id here, but that shouldn't be a problem?)

I call it once a second for up to 2 minutes.

I most commonly see it in autoscaling. I don't have a traceback to hand but off the top of my head its a call to ``UpdateAutoScalingGroup``, specifically when I'm updating ``MinSize``, ``MaxSize`` and ``DesiredCapacity`` (to implement a rolling restart - i increase the size of the ASG and then terminate instances in turn, then resize the ASG to return it to normal size). I'll try and get an example of that tomorrow.

**Comment by Jc2k** [comment] 2015-03-09 16:12
Just happened now with ``client.delete_customer_gateway(CustomerGatewayId='cow-id...')``

**Comment by jamesls** [comment] 2015-03-09 17:17
Thanks for the extra debug info.  I'm trying to capture a debug log or wire trace of what's going on at the HTTP layer.  I'll report back what I find.

**Comment by Jc2k** [comment] 2015-03-10 14:06
Just happened with ``client.delete_vpc(VpcId='...')`` as well.

**Comment by danielgtaylor** [comment] 2015-03-10 22:28
@Jc2k any more info about this issue? What Python version are you using? Any particularly weird OpenSSL version? Any chance of using Wireshark or another wire logging utility to capture packets and give us more info since I can't reproduce it myself?

I just did 10,000 DescribeNetworkInterface calls each with the same parameters as above in Python 3.4.2 and Python 2.7.9 without getting a single `BadStatusLine` error. Here are some issues that might be related:

* https://github.com/kennethreitz/requests/issues/2448#issuecomment-74824282
* http://bugs.python.org/issue23054

This change seems to encourage the raising of that error:

* https://github.com/kennethreitz/requests/pull/2323

And it looks like the error may be changing in the near future:

* http://bugs.python.org/issue3566
* https://github.com/kennethreitz/requests/issues/2233

Any more help you can provide to reproduce or log this would be appreciated.

**Comment by Jc2k** [comment] 2015-03-11 10:40
The big thing is probably that I have pyopenssl installed, which has been problematic with a bunch of stuff. I actually used to hit #266 previously.

(I only have it installed because requests was unable to grab https://ip-ranges.amazonaws.com/ip-ranges.json without it).

**Comment by Jc2k** [comment] 2015-03-11 10:41
The version of python in trusty is 2.7.6 with the CVE's backported. It doesn't have the SSL changes from python 2.7.9.

**Comment by danielgtaylor** [comment] 2015-03-11 22:34
@Jc2k unfortunately I can't seem to reproduce this error at all. I've spun up a brand new instance with Ubuntu 14.04 (Trusty) and used Python 2.7.6 with all official updates. I created a virtualenv, installed pyopenssl and all its requirements, installed botocore and then made 30,000 `DescribeNetworkInterfaces` calls like you mentioned above without getting a single error.

At this point I'm at a loss of what to try next :frowning: 

If you think it might be related to pyopenssl, and you only need it for that one URL, how about downloading the file yourself and temporarily removing that dependency? Can you still get the errors then?

**Comment by Jc2k** [comment] 2015-03-12 07:23
@danielgtaylor I had the same idea, and thought it had helped. But still happens.

I can try wiresharking - but is the encrypted dump enough?

**Comment by danielgtaylor** [comment] 2015-03-17 20:09
@Jc2k I'm not sure if Wireshark can act as a man-in-the-middle for SSL connections, but judging from the docs here it looks like it might work:

https://wiki.wireshark.org/SSL

Alternatively, I've used this before and it has worked well:

https://mitmproxy.org/

Look at the docs for transparent HTTPS proxy mode. Just make sure to disable client-side SSL verification (via `--no-verify-ssl` in the AWS CLI) or temporarily install the mitmproxy certificate.

**Comment by jamesls** [comment] 2015-06-12 22:46
Just wanted to follow up on this issue, are you still seeing `BadStatusLine` exceptions with the latest version of botocore?

**Comment by Jc2k** [comment] 2015-06-14 13:53
As a workaround for #482 i've injected my own _retry.json locally which doubles ``retry.__default__.max_attempts``. I think this is masking the issue for me.

**Comment by rayluo** [comment] 2015-11-05 03:37
So this is an update.

* Based on the usage pattern described at Mar 4 in this thread, I wrote a code snippet to create an ELB, call `DescribeNetworkInterfaces` several times with 1 second sleep in between, delete the ELB, call `DescribeNetworkInterfaces` per second again, and repeat. Should there be any race condition when trying to describe an being-deleted network interface, we would probably observe it. The test scripts is run on same environment (Ubuntu 14.04 Trusty with the default python 2.7.6) for roughly 240,000 `DescribeNetworkInterfaces` calls in 2.5 days, without a single BadStatusLine error.
* Even so, we still made an effort to [wrap the BadStatusLine error](https://github.com/boto/botocore/pull/707), so that users can have better error message, should this symptom happen again next time.
* We also documented our thoughts on #482, although there is no specific schedule at this point.
* I'm closing this issue for now.

**Closed by rayluo** 2015-11-05 03:37 UTC
Labels: bug
