### ISSUE TITLE
Support CloudFront signed cookies creation

### ISSUE THREAD

**Issue by lorenzodantonio** [boto/botocore#2307] opened 2021-02-23 11:36 UTC
**Is your feature request related to a problem? Please describe.**
Currently, there is no easy way to generate signed CloudFront cookies with python.

**Describe the solution you'd like**
I propose to add a method to CloudFrontSigner to create signed cookies, this should return a dict containing cookie name and values for Set-Cookie headers. Here is my proposal: #2284

**Comment by kdaily** [comment] 2021-05-13 15:58
Marking as feature request, thanks!

**Comment by tim-finnigan** [comment] 2022-01-11 18:52
Closing this as a duplicate of older request in boto3: https://github.com/boto/boto3/issues/706. There is more discussion in that issue and the team can follow up there.

**Closed by tim-finnigan** 2022-01-11 18:52 UTC
Labels: feature-request
