### ISSUE TITLE
s3control put_public_access_block additional permissions update

### ISSUE THREAD

**Issue by severel** [boto/botocore#2725] opened 2022-07-28 10:13 UTC
### Describe the issue

s3control put_public_access_block requires additional IAM permissions from S3 service.
The documentation states that:
"For this operation, users must have the s3:PutBucketPublicAccessBlock permission"
When I tried using it - it seems that this is not the correct s3 permission needed.
The correct one seems to be:
s3:PutAccountPublicAccessBlock
I've tested and validated it.

### Links

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3control.html#S3Control.Client.put_public_access_block

**Comment by aBurmeseDev** [comment] 2022-08-04 01:17
Hi @severel, thanks for bringing this to our attention!

I was able to reproduce and can confirm that the IAM permission needed for `put_public_access_block` is `s3:PutAccountPublicAccessBlock`. 

Since this also affects the documentation of other SDKs, I created an issue here in our cross-SDK repository: [here](https://github.com/aws/aws-sdk/issues/316). I reached out to the team regarding this and will update that issue accordingly. 

As I'm going to close this, please refer to that issue in aws/aws-sdk repo going forward for updates.

**Closed by aBurmeseDev** 2022-08-04 01:17 UTC
Labels: investigating, documentation, s3control
