### ISSUE TITLE
Timezone parsing error in develop branch

### ISSUE THREAD

**Issue by michael-dev2rights** [boto/botocore#1070] opened 2016-11-08 16:05 UTC
I'm running on Ubuntu 16.04 LTS.  I have python I have pulled and checked out develop branch at commit

e079c0db2e2fc28684c4f6a87298d0cf592e6e29

I installed the dependencies in requirements.txt (see attached file)

[pip-list.txt](https://github.com/boto/botocore/files/578672/pip-list.txt)

When I run 

`nosetests tests/unit/`

Then the output ends 

```
======================================================================
FAIL: test_parse_rfc822 (tests.unit.test_utils.TestParseTimestamps)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mikedd/dev/botocore/tests/unit/test_utils.py", line 249, in test_parse_rfc822
    datetime.datetime(2002, 10, 2, 13, 0, tzinfo=tzutc()))
AssertionError: datetime.datetime(2002, 10, 2, 13, 0, tzinfo=tzlocal()) != datetime.datetime(2002, 10, 2, 13, 0, tzinfo=tzutc())

----------------------------------------------------------------------
Ran 1615 tests in 21.648s

FAILED (failures=1)

```

actual output log attached.  

[nose-unit-run-botocore-develop-e079c0db-log.txt](https://github.com/boto/botocore/files/578670/nose-unit-run-botocore-develop-e079c0db-log.txt)

**Comment by JordonPhillips** [comment] 2016-11-08 20:58
That's a direct parse from dateutil, and it does look right. What version of `python-dateutil` do you have? Also, what time zone are you in?

**Comment by michael-dev2rights** [comment] 2016-11-09 11:07
Hi @JordonPhillips 

```
$ pip freeze | grep dateutil
python-dateutil==2.5.3
```

```
$ date
Wed  9 Nov 11:06:01 GMT 2016
```

**Comment by michael-dev2rights** [comment] 2016-11-09 11:55
Actually, looking at this, the problem is obvious.  Since my timezone is GMT then actually my local time representation is identical to UTC.   The objects are not equal (one of them has tzlocal and one of them has tzutc) but their meaning is equal.   

I'm not really able to work out whether the test is "wrong" or datetime.fromtimestamp() is really "wrong".  It's a bit exceptional behavior (to return a different timezone in the return iff the user is in GMT) but since I guess that that's going to be present in many datetime installs, you probably want to special case the test when run in GMT or fix the timezone used during the test to be one which is different from GMT.

**Comment by michael-dev2rights** [comment] 2016-11-09 12:04
The "problem" is that 
`parse_timestamp('Wed, 02 Oct 2002 13:00:00 GMT'),`
when run normally will return with tzinfo=tzutc().  When it's run where I live it returns with tzinfo=tzlocal() 

because that's true

**Comment by JordonPhillips** [comment] 2016-11-09 16:21
Fascinating. So just to be clear, the following returns false:

```python
from datetime import datetime
from dateutil.parser import parse
from dateutil.tz import tzutc


d1 = datetime(2002, 10, 2, 13, 0, tzinfo=tzutc())
d2 = parse('Wed, 02 Oct 2002 13:00:00 GMT')
print(d1 == d2)
```

**Comment by jstewmon** [comment] 2016-11-09 17:07
I'm able to reproduce this on macOS by setting my timezone to GMT.

dateutil.parse checks if the parsed tz is in `time.tzname` (`('GMT', 'BST')` in this case), and if it is, the parsed datetime uses tz.tzlocal:
https://github.com/dateutil/dateutil/blob/master/dateutil/parser.py#L605

The inequality occurs because the moment being parsed is in BST, which is `2002-10-02 13:00:00+01:00`.

On the surface, I would think it's a bug that the dateutil parser would prefer `tzlocal` when a timezone is parsed from the string.

**Comment by JordonPhillips** [comment] 2016-11-09 17:12
@jstewmon can confirm. Man, this is wild

**Comment by JordonPhillips** [comment] 2016-11-09 17:32
I'll open an issue with dateutil and link it back here.

**Comment by JordonPhillips** [comment] 2016-11-09 17:51
I'm going to go ahead and close this issue out since the dateutil people are aware of it and there doesn't seem to be anything we can do to fix it on our side (without re-implementing dateutil).

**Comment by pganssle** [comment] 2016-11-09 18:15
@JordonPhillips Actually, you can do this:

```python
from datetime import datetime
from dateutil.parser import parse
from dateutil.tz import tzutc


d1 = datetime(2002, 10, 2, 13, 0, tzinfo=tzutc())
d2 = parse('Wed, 02 Oct 2002 13:00:00 GMT', tzinfos={'GMT': tzutc()})
print(d1 == d2)
```

But as I detailed on the issue over there, it's not unreasonable to change things later such that this specific example will work, because there's no such time as `'Wed, 02 Oct 2002 13:00:00 GMT'` in the  `GMT0BST` zone (or whatever the TZ string is for London time), and it's probably reasonable to be smart about that if possible.

**Comment by JordonPhillips** [comment] 2016-11-09 18:32
Thanks for the tip! For our specific case, we can be fairly certain that we'll always be getting GMT time back so that single `tzinfos` entry should be sufficient.

**Closed** 2016-11-15 20:13 UTC
Labels: bug, dependency
