### ISSUE TITLE
odd behavior when setting `AWS_METADATA_SERVICE_TIMEOUT`

### ISSUE THREAD

**Issue by itajaja** [boto/botocore#2421] opened 2021-06-18 02:41 UTC
**Describe the bug**
when I set `AWS_METADATA_SERVICE_TIMEOUT` to any value, making a call that fetches the credentials, will always wait for the entire time. that is, if i set timeout to 3s, the request will take a little more than 3s, if I set it to 1s, the request it will take little more than 1s.

**Steps to reproduce**

I was able to reproduce with this minimal example:

```py
from botocore import utils
f = utils.InstanceMetadataFetcher(timeout=5, num_attempts=1)
f.retrieve_iam_role_credentials()
```

this will take invariably 5s. if I set timeout to 10, it will take 5s, etc.

**Expected behavior**

I would expect the function above to return as soon as the request completes, not wait until timeout

**Debug logs**

```
>>> f = utils.InstanceMetadataFetcher(timeout=3, num_attempts=1)
2021-06-18 02:35:35,631 botocore.utils [DEBUG] IMDS ENDPOINT: http://169.254.169.254/
2021-06-18 02:35:35,631 - botocore.utils - DEBUG - IMDS ENDPOINT: http://169.254.169.254/
>>> f.retrieve_iam_role_credentials()
2021-06-18 02:35:37,423 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 169.254.169.254:80
2021-06-18 02:35:40,427 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (2): 169.254.169.254:80
2021-06-18 02:35:40,428 - urllib3.connectionpool - DEBUG - http://169.254.169.254:80 "GET /latest/meta-data/iam/security-credentials/ HTTP/1.1" 200 63
2021-06-18 02:35:40,429 - urllib3.connectionpool - DEBUG - Resetting dropped connection: 169.254.169.254
2021-06-18 02:35:40,429 - urllib3.connectionpool - DEBUG - http://169.254.169.254:80 "GET /latest/meta-data/iam/security-credentials/xx HTTP/1.1" 200 1310
{'role_name': 'xxx', 'access_key': 'xx', 'secret_key': 'xx', 'token': xx', 'expiry_time': '2021-06-18T08:20:45Z'}
```

you can see specifically from the log above that there is a lag of 3s between the first and the second line of logs after calling `retrieve_iam_role_credentials`

**Comment by stobrien89** [comment] 2021-06-21 20:28
Hi @itajaja,

Thanks for reaching out!  What is the botocore version you're using?  Also, what is the instance type this is occurring on? Thanks!

**Comment by itajaja** [comment] 2021-06-21 20:32
hi! it's an m instance. I am running it on m5.large, running on EKS (k8s 1.20, although it showed the same behavior with earlier versions). botocore version `1.20.78`

**Comment by stobrien89** [comment] 2021-06-25 20:41
Hi @itajaja,

Thanks for your patience.  I was unable to reproduce this on a T3.medium running on EKS (kubernetes version 1.20). I haven't tried yet on a M5 because I wanted to test something with lesser network performance.

<img width="1090" alt="Screen Shot 2021-06-25 at 1 30 17 PM" src="https://user-images.githubusercontent.com/60306702/123482798-9e377500-d5ba-11eb-88c9-c428d67d7d95.png">

Is there anything additional information you could provide that would help me to reproduce this?  Thanks!

**Comment by itajaja** [comment] 2021-06-26 11:25
@stobrien89 thanks for looking into this, I'll try to simplify the reproduction steps on my end, see if any variation is the culprit

**Comment by itajaja** [comment] 2021-06-28 14:21
@stobrien89 are you sure you are using the same version? I am using python 3.9 and botocore 1.20. I tried to install an old version (1.4) and I do not see the issue. so it's definitely something that got added in some version between 1.4 and 1.20. I'll try to bisect. let me know if you still cannot reproduce with the right botocore version

**Comment by itajaja** [comment] 2021-06-28 14:27
alright, after bisecting. it seems the odd behavior is triggered with version 1.13.23, but not with 1.13.22. I'll look at changelog and diff. hope this helps

**Comment by itajaja** [comment] 2021-06-28 14:35
this seems the culprit change https://github.com/boto/botocore/commit/4a8614c8bb50b4c0c0aa5cf6a1ccd9237c75f3e8

**Comment by itajaja** [comment] 2021-06-28 15:03
more intel: it looks like I cannot reach (for whatever reason)  `http://169.254.169.254/latest/api/token`. for me the minimum reproducible step is:

```
curl http://169.254.169.254/latest/api/token
```

so I think what's happening there is that boto tries that, then it fails due to timeout, and then it gets the token with `latest/meta-data/iam/security-credentials/` and that works

**Comment by itajaja** [comment] 2021-06-28 15:39
alright. so, the new metadata endpoint can be reached from kubernetes only with two hops at the IP level, so the instance metadata options need to be updated accordingly. more info at https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html

**Comment by itajaja** [comment] 2021-06-28 15:40
I think we should close this, as I don't think this is a problem with botocore

**Comment by stobrien89** [comment] 2021-06-29 17:48
Hi @itajaja,

Thanks a lot for the detailed information!  Closing for now, but please let us know if anything else comes up.

**Closed by stobrien89** 2021-06-29 17:48 UTC
Labels: guidance
