### ISSUE TITLE
Deprecate Usage of `sslComonName` in Endpoint Creation

### ISSUE THREAD

**Issue by dlm6693** [boto/botocore#2705] opened 2022-06-22 18:14 UTC
## The Problem

Currently when creating a service client, an `sslCommonName` attribute may be used for endpoint construction in unique cases. The format of `sslCommonName` is typically `{region}.{service}.{dnsSuffix}`,  as opposed to the more common `{service}.{region}.{dnsSuffix}`. This usage originated from a time where Python versions (<2.7) didn't supply an SSL module, requiring specific certificate formats.

Now that the library only support Python 3.7+, we'll be deprecating the usage of `sslCommonName` to standardize Boto3 with all other AWS SDKs. This will also resolve long running issues of services such as SQS and GuardDuty being incompatible with certain VPC endpoint configurations.

## Required Actions

In the immediate term, we will start raising a deprecation warning when `sslCommonName` is used. This is to alert customers of the upcoming change and provide time to make any required changes.

For most users, this will not require any changes. The URL will automatically update when the next minor version (1.29.0) is released, and clients will continue to operate the same. For any users with strict network rules, explicitly allow listing domains, you will need to add support for `{service}.{region}.{dnsSuffix}` as demonstrated below:

**Old Format:** https://us-west-2.sqs.amazonaws.com
**New Format:** https://sqs.us-west-2.amazonaws.com

## Warning Mitigation Strategy

1. If you wish to ensure that your application does not use `sslCommonName` now or test the impending deprecation, we have created a new environment variable `BOTO_DISABLE_COMMONNAME`. Setting this to `true` will suppress the warning and convert to the new `hostname` format.
2. If you are concerned about this change causing disruptions, you can pin your version of `botocore` to `<1.29.0` until you are ready to migrate.
4. If you are only concerned about silencing the warning in your logs, use `warnings.filterwarnings` when instantiating a new service client.

```python
import warnings
warnings.filterwarnings('ignore', category=FutureWarning, module='botocore.client')
```

### Other Information

Endpoint Docs: https://docs.aws.amazon.com/general/latest/gr/rande.html
Related Issues: https://github.com/boto/botocore/issues/2376, https://github.com/boto/boto3/issues/1900, https://github.com/boto/boto3/issues/3311, https://github.com/boto/botocore/issues/2683

**Comment by bblommers** [comment] 2022-09-04 18:18
The EMR client now gives the following warning:

`The elasticmapreduce client is currently using a deprecated endpoint: elasticmapreduce.us-east-1.amazonaws.com. In the next minor version this will be moved to elasticmapreduce.us-east-1.amazonaws.com.`

Note that the URL's are the same. What is the actual change for this service?

**Comment by dlm6693** [comment] 2022-09-04 20:14
Oh interesting! Thank you for raising this. I guess for whatever reason the SSL common name for EMR is the same as the standard host name. It will follow the `{service}.{region}.{dnsSuffix}` region as outlined above so it won't actually change. I don't think we will spend engineering resources to cherry pick common names that follow this pattern as they will be fully deprecated in the next minor version bump. Feel free to suppress this one or any others like it if needed. A decent workaround would be to add a regular expression to match the message in the message parameter of `warnings.filterwarnings`. Something like the following should do the trick.

```python
warnings.filterwarnings('ignore', category=FutureWarning, module='botocore.client', message='.*elasticmapreduce.us-east-1.amazonaws.com.*')

**Comment by bblommers** [comment] 2022-09-04 20:53
Awesome - thanks for the info @dlm6693!

**Comment by NotSoShaby** [comment] 2022-09-06 13:32
Please notice that boto3 sqs client is creating queues with the soon to be deprecated format.
We started using this:

        `queue = sqs_client.create_queue(QueueName=f"{org.name.lower()}-queue", tags={'ClientName': org.name})`

to create queues for our clients, but the returned queue is giving us this deprecaion warning:

`FutureWarning: The sqs client is currently using a deprecated endpoint: queue.amazonaws.com. In the next minor version this will be moved to sqs.us-east-1.amazonaws.com. See https://github.com/boto/botocore/issues/2705 for more details.`

boto3 should create a properly formatted queues a while before you break the old ones IMO

**Comment by dlm6693** [comment] 2022-09-06 14:27
Hi @NotSoShaby if I'm understanding you correctly, you can create a SQS endpoint with the non-deprecated format by enabling the environment variable described above.

**Comment by NotSoShaby** [comment] 2022-09-07 06:47
@nateprewitt thanks, will try it out. assuming it should be set to true?
@dlm6693 no, I wasn't using the env variable flag will update once i tested it.

thanks for the quick response :)

**Comment by dlm6693** [comment] 2022-09-07 15:00
Yep set to true

**Comment by lehmat** [comment] 2022-09-22 08:32
I'm getting the deprecation warning even though the DNS name is taken from CloudFormation output of an AWS::SQS:Queue Ref value and have confirmed this environment variable to be set as: `https://sqs.eu-north-1.amazonaws.com/XXXXX/FILTERED-SQSQueue-1MANR5OR9C65A` on lambda which is then correctly read by our code. Is this by design?

**Comment by tikicoder** [comment] 2022-09-29 16:58
I am getting the warning on rds
FutureWarning: The rds client is currently using a deprecated endpoint: rds.amazonaws.com. In the next minor version this will be moved to rds.us-east-1.amazonaws.com. See https://github.com/boto/botocore/issues/2705 for more details.

I verified when I create the client I pass in the region

**Comment by dlm6693** [comment] 2022-09-29 17:21
Hi @tikicoder. That is expected behavior. The `sslCommonName` template for this service and region is defined as `{service}.{dnsSuffix}` in `endpoints.json`. You can confirm the actual endpoint being used for operation calls by running the following.

```python
import boto3
rds_client = boto3.client('rds', region_name='us-east-1')
rds_client._endpoint
> rds(https://rds.amazonaws.com)

**Comment by tikicoder** [comment] 2022-09-29 17:33
@dlm6693 Thanks. I am presuming boto will be updated to fix the issue? It looks like I could by passing in an extra config, but that seems like overkill on something that I would presume should work since I am passing in all the required values.

**Comment by dlm6693** [comment] 2022-09-29 17:50
@tikicoder of course hence the deprecation warning and the creation of this issue. As documented at the top of this issue, you can disable the behavior now by setting the environment variable `BOTO_DISABLE_COMMONNAME` to `true`

**Comment by tikicoder** [comment] 2022-09-29 17:58
@dlm6693 
The warning doesn't bother me as long as I can explain it. 
Instead of setting an environment variable, I would have preferred a flag. I either have to manually set the environment variable or I have to tell people how to do that. Fortunately, I have spun up my own boto helper system so it's not that big of an issue.

Thanks for the quick replies

**Comment by gheorghina** [comment] 2022-09-29 19:36
hello, I am new to python botocore and the ecosystem; I am trying to run localstack and celery workers via docker compose, and I get similar error:  
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://eu-east-1.queue.amazonaws.com/" 
 /usr/local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py:367: CPendingDeprecationWarning

how would you advise to adjust the configurations?

Thank you

**Comment by dlm6693** [comment] 2022-09-29 20:13
@gheorghina I suspect that is because the `eu-east-1` region does not exist. Here is a list of available regions https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html#concepts-available-regions

**Comment by gheorghina** [comment] 2022-09-29 20:19
for sure I am missing some configurations, as you are right, I expected it to be `eu-central-1`

**Comment by dlm6693** [comment] 2022-09-29 20:23
@gheorghina if you continue to run into issues feel free to open up a new issue. It seems to be unrelated to this one. Please add `boto3.set_stream_logger()` to your script and share the output.

**Comment by vbhjckfd** [comment] 2022-10-06 11:22
I got a warning

`/usr/local/lib/python3.10/site-packages/botocore/client.py:625: FutureWarning: The sqs client is currently using a deprecated endpoint: eu-west-1.queue.amazonaws.com. In the next minor version this will be moved to sqs.eu-west-1.amazonaws.com. 
`
But all of my endpoits are already using service.zone.amazonaws.com format, no idea what to fix :(

**Comment by dlm6693** [comment] 2022-10-06 13:07
@vbhjckfd have you tried using the environment variable described above?

**Comment by vbhjckfd** [comment] 2022-10-11 11:50
> @vbhjckfd have you tried using the environment variable described above?


Setting env variable BOTO_DISABLE_COMMONNAME to true eliminates warning and still keeps my script working.

**Comment by Taragolis** [comment] 2022-10-26 14:06
Just wondering is botocore>=1.28.0 still use `sslCommonName` by default?
And for disable it still required to set env `BOTO_DISABLE_COMMONNAME=true`

**Comment by dlm6693** [comment] 2022-10-26 16:32
@Taragolis yes. We'll need to update this document, but only a select group of services (s3 and s3-control) have had the new methodology of endpoint resolution enabled. Until that time, `sslCommonName` will be used by default when defined for all other services.

**Comment by dlm6693** [comment] 2022-10-26 16:46
After conferring with the team, `BOTO_DISABLE_COMMNAME` will no longer be needed to suppress the deprecation warning for the NEXT minor version `1.29.0`. That will be released in the near future. I've updated the issue accordingly.

**Comment by Taragolis** [comment] 2022-10-26 18:50
@dlm6693 many thanks for detail explanation!

**Comment by nateprewitt** [comment] 2022-11-16 23:49
Resolving now that we've had botocore 1.29.x out for a couple weeks. Please feel free to let us know if you encounter any issues but the migration should be complete at this point.

**Closed by nateprewitt** 2022-11-16 23:49 UTC
Labels: breaking-change, feature-request, needs-discussion, endpoints, p2
