### ISSUE TITLE
"TypeError: can't compare offset-naive and offset-aware datetimes" when fetching credentials via iam-role

### ISSUE THREAD

**Issue by BowlesCR** [boto/botocore#3077] opened 2023-11-27 21:14 UTC
### Describe the bug

Calling `aws secretsmanager get-secret-value --secret-id MySecret` from an EC2 instance using instance role credentials fails with output "can't compare offset-naive and offset-aware datetimes".

Running with `--debug` appears to show botocore attempting to fetch credentials from the iam-role and validate the expiration date on them.

### Expected Behavior

Secret value should be retrieved (or creds retrieved in the scope of botocore's responsibility)

### Current Behavior

```
# aws secretsmanager get-secret-value --secret-id MySecret --debug

2023-11-27 20:25:41,713 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.13.7 Python/3.12.0 Linux/6.5.6-300.fc39.aarch64 source/aarch64.fedora.39
2023-11-27 20:25:41,713 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['secretsmanager', 'get-secret-value', '--secret-id', 'MySecret', '--debug']
2023-11-27 20:25:41,728 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_s3 at 0xffff8ba9ccc0>
2023-11-27 20:25:41,728 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_ddb at 0xffff8badcb80>
2023-11-27 20:25:41,728 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.configure.configure.ConfigureCommand'>>
2023-11-27 20:25:41,728 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0xffff8bc5ad40>
2023-11-27 20:25:41,728 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0xffff8bc744a0>
2023-11-27 20:25:41,728 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function alias_opsworks_cm at 0xffff8ba9f420>
2023-11-27 20:25:41,729 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_history_commands at 0xffff8bb1fb00>
2023-11-27 20:25:41,729 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.devcommands.CLIDevCommand'>>
2023-11-27 20:25:41,729 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_waiters at 0xffff8ba9f2e0>
2023-11-27 20:25:41,729 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method AliasSubCommandInjector.on_building_command_table of <awscli.alias.AliasSubCommandInjector object at 0xffff8be986b0>>
2023-11-27 20:25:41,729 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/lib/python3.12/site-packages/awscli/data/cli.json
2023-11-27 20:25:41,731 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_types at 0xffff8b9ed6c0>
2023-11-27 20:25:41,731 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function no_sign_request at 0xffff8b9ed9e0>
2023-11-27 20:25:41,731 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_verify_ssl at 0xffff8b9ed940>
2023-11-27 20:25:41,731 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_read_timeout at 0xffff8b9edb20>
2023-11-27 20:25:41,731 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_connect_timeout at 0xffff8b9eda80>
2023-11-27 20:25:41,731 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <built-in method update of dict object at 0xffff8b94d540>
2023-11-27 20:25:41,732 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.13.7 Python/3.12.0 Linux/6.5.6-300.fc39.aarch64 source/aarch64.fedora.39 prompt/off
2023-11-27 20:25:41,732 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['secretsmanager', 'get-secret-value', '--secret-id', 'MySecret', '--debug']
2023-11-27 20:25:41,732 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_timestamp_parser at 0xffff8ba9d440>
2023-11-27 20:25:41,732 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0xffff8c275c60>
2023-11-27 20:25:41,732 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_binary_formatter at 0xffff8b90bec0>
2023-11-27 20:25:41,732 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function no_pager_handler at 0xffff8c3485e0>
2023-11-27 20:25:41,732 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0xffff8c2898a0>
2023-11-27 20:25:41,734 - MainThread - botocore.utils - DEBUG - IMDS ENDPOINT: http://169.254.169.254/
2023-11-27 20:25:41,736 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0xffff8bb1c220>
2023-11-27 20:25:41,736 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_json_file_cache at 0xffff8bad4fe0>
2023-11-27 20:25:41,749 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/lib/python3.12/site-packages/awscli/botocore/data/secretsmanager/2017-10-17/service-2.json
2023-11-27 20:25:41,751 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/lib/python3.12/site-packages/awscli/botocore/data/secretsmanager/2017-10-17/service-2.sdk-extras.json
2023-11-27 20:25:41,752 - MainThread - botocore.hooks - DEBUG - Event building-command-table.secretsmanager: calling handler <function add_waiters at 0xffff8ba9f2e0>
2023-11-27 20:25:41,765 - MainThread - botocore.hooks - DEBUG - Event building-command-table.secretsmanager: calling handler <bound method AliasSubCommandInjector.on_building_command_table of <awscli.alias.AliasSubCommandInjector object at 0xffff8be986b0>>
2023-11-27 20:25:41,766 - MainThread - awscli.clidriver - DEBUG - OrderedDict({'secret-id': <awscli.arguments.CLIArgument object at 0xffff8baaa540>, 'version-id': <awscli.arguments.CLIArgument object at 0xffff8c5cd730>, 'version-stage': <awscli.arguments.CLIArgument object at 0xffff8afe6f30>})
2023-11-27 20:25:41,766 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.secretsmanager.get-secret-value: calling handler <function add_streaming_output_arg at 0xffff8ba9d8a0>
2023-11-27 20:25:41,766 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.secretsmanager.get-secret-value: calling handler <function add_cli_input_json at 0xffff8c28a160>
2023-11-27 20:25:41,766 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.secretsmanager.get-secret-value: calling handler <function add_cli_input_yaml at 0xffff8c28af20>
2023-11-27 20:25:41,766 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.secretsmanager.get-secret-value: calling handler <function unify_paging_params at 0xffff8badd3a0>
2023-11-27 20:25:41,780 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/lib/python3.12/site-packages/awscli/botocore/data/secretsmanager/2017-10-17/paginators-1.json
2023-11-27 20:25:41,780 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.secretsmanager.get-secret-value: calling handler <function add_generate_skeleton at 0xffff8b9bbec0>
2023-11-27 20:25:41,780 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.secretsmanager.get-secret-value: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinput.CliInputJSONArgument object at 0xffff8afe6ed0>>
2023-11-27 20:25:41,780 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.secretsmanager.get-secret-value: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinput.CliInputYAMLArgument object at 0xffff8afe6ea0>>
2023-11-27 20:25:41,780 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.secretsmanager.get-secret-value: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0xffff8afe7290>>
2023-11-27 20:25:41,780 - MainThread - botocore.hooks - DEBUG - Event building-command-table.secretsmanager_get-secret-value: calling handler <function add_waiters at 0xffff8ba9f2e0>
2023-11-27 20:25:41,781 - MainThread - botocore.hooks - DEBUG - Event building-command-table.secretsmanager_get-secret-value: calling handler <bound method AliasSubCommandInjector.on_building_command_table of <awscli.alias.AliasSubCommandInjector object at 0xffff8be986b0>>
2023-11-27 20:25:41,781 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.secretsmanager.get-secret-value.secret-id: calling handler <awscli.paramfile.URIArgumentHandler object at 0xffff8bba02c0>
2023-11-27 20:25:41,781 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.secretsmanager.get-secret-value: calling handler <awscli.argprocess.ParamShorthandParser object at 0xffff8c57c7d0>
2023-11-27 20:25:41,782 - MainThread - awscli.arguments - DEBUG - Unpacked value of 'MySecret' for parameter "secret_id": 'MySecret'
2023-11-27 20:25:41,782 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.secretsmanager.get-secret-value.version-id: calling handler <awscli.paramfile.URIArgumentHandler object at 0xffff8bba02c0>
2023-11-27 20:25:41,782 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.secretsmanager.get-secret-value.version-stage: calling handler <awscli.paramfile.URIArgumentHandler object at 0xffff8bba02c0>
2023-11-27 20:25:41,782 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.secretsmanager.get-secret-value.cli-input-json: calling handler <awscli.paramfile.URIArgumentHandler object at 0xffff8bba02c0>
2023-11-27 20:25:41,782 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.secretsmanager.get-secret-value.cli-input-yaml: calling handler <awscli.paramfile.URIArgumentHandler object at 0xffff8bba02c0>
2023-11-27 20:25:41,782 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.secretsmanager.get-secret-value.generate-cli-skeleton: calling handler <awscli.paramfile.URIArgumentHandler object at 0xffff8bba02c0>
2023-11-27 20:25:41,782 - MainThread - botocore.hooks - DEBUG - Event calling-command.secretsmanager.get-secret-value: calling handler <bound method CliInputArgument.add_to_call_parameters of <awscli.customizations.cliinput.CliInputJSONArgument object at 0xffff8afe6ed0>>
2023-11-27 20:25:41,782 - MainThread - botocore.hooks - DEBUG - Event calling-command.secretsmanager.get-secret-value: calling handler <bound method CliInputArgument.add_to_call_parameters of <awscli.customizations.cliinput.CliInputYAMLArgument object at 0xffff8afe6ea0>>
2023-11-27 20:25:41,782 - MainThread - botocore.hooks - DEBUG - Event calling-command.secretsmanager.get-secret-value: calling handler <bound method GenerateCliSkeletonArgument.generate_skeleton of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0xffff8afe7290>>
2023-11-27 20:25:41,782 - MainThread - botocore.utils - DEBUG - IMDS ENDPOINT: http://169.254.169.254/
2023-11-27 20:25:41,784 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 169.254.169.254:80
2023-11-27 20:25:41,785 - MainThread - urllib3.connectionpool - DEBUG - http://169.254.169.254:80 "PUT /latest/api/token HTTP/1.1" 200 56
2023-11-27 20:25:41,786 - MainThread - urllib3.connectionpool - DEBUG - Resetting dropped connection: 169.254.169.254
2023-11-27 20:25:41,787 - MainThread - urllib3.connectionpool - DEBUG - http://169.254.169.254:80 "GET /latest/meta-data/placement/availability-zone/ HTTP/1.1" 200 10
2023-11-27 20:25:41,788 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2023-11-27 20:25:41,788 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2023-11-27 20:25:41,788 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role-with-web-identity
2023-11-27 20:25:41,788 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: sso
2023-11-27 20:25:41,788 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2023-11-27 20:25:41,788 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: custom-process
2023-11-27 20:25:41,788 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: config-file
2023-11-27 20:25:41,788 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: ec2-credentials-file
2023-11-27 20:25:41,788 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: boto-config
2023-11-27 20:25:41,788 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: container-role
2023-11-27 20:25:41,788 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: iam-role
2023-11-27 20:25:41,789 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 169.254.169.254:80
2023-11-27 20:25:41,790 - MainThread - urllib3.connectionpool - DEBUG - http://169.254.169.254:80 "PUT /latest/api/token HTTP/1.1" 200 56
2023-11-27 20:25:41,790 - MainThread - urllib3.connectionpool - DEBUG - Resetting dropped connection: 169.254.169.254
2023-11-27 20:25:41,791 - MainThread - urllib3.connectionpool - DEBUG - http://169.254.169.254:80 "GET /latest/meta-data/iam/security-credentials/ HTTP/1.1" 200 11
2023-11-27 20:25:41,792 - MainThread - urllib3.connectionpool - DEBUG - Resetting dropped connection: 169.254.169.254
2023-11-27 20:25:41,793 - MainThread - urllib3.connectionpool - DEBUG - http://169.254.169.254:80 "GET /latest/meta-data/iam/security-credentials/MyRole HTTP/1.1" 200 1586
2023-11-27 20:25:41,795 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/awscli/clidriver.py", line 460, in main
    return command_table[parsed_args.command](remaining, parsed_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/awscli/clidriver.py", line 595, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/awscli/clidriver.py", line 798, in __call__
    return self._operation_caller.invoke(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/awscli/clidriver.py", line 925, in invoke
    client = self._session.create_client(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/awscli/botocore/session.py", line 839, in create_client
    credentials = self.get_credentials()
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/awscli/botocore/session.py", line 445, in get_credentials
    'credential_provider').load_credentials()
                           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/awscli/botocore/credentials.py", line 1943, in load_credentials
    creds = provider.load()
            ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/awscli/botocore/credentials.py", line 996, in load
    metadata = fetcher.retrieve_iam_role_credentials()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/awscli/botocore/utils.py", line 500, in retrieve_iam_role_credentials
    self._evaluate_expiration(credentials)
  File "/usr/lib/python3.12/site-packages/awscli/botocore/utils.py", line 583, in _evaluate_expiration
    if current_time >= extension_time:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: can't compare offset-naive and offset-aware datetimes

can't compare offset-naive and offset-aware datetimes
```

### Reproduction Steps

Using Fedora 39 image (ami-0c991a7292a8fd8c4 in us-east-1 for example) on an EC2 instance configured with an instance role permitting secrets access.

```
dnf update -y
dnf install -y awscli2
aws secretsmanager get-secret-value --secret-id MySecret
```

### Additional Information/Context

Is this perhaps a packaging issue?

### SDK version used

Whichever is packaged with aws-cli/2.13.7
/usr/lib/python3.12/site-packages/awscli/botocore/__init__.py shows __version__ = '2.0.0dev155' -- although the stack trace references _evaluate_expiration() which doesn't appear in the v2 branch.

### Environment details (OS name and version, etc.)

Fedora 39 - Linux 6.5.6-300.fc39.aarch64 `#1` SMP PREEMPT_DYNAMIC Fri Oct  6 19:36:57 UTC 2023 aarch64 GNU/Linux

**Comment by chris-palmer99** [comment] 2023-12-04 15:36
Confirmed the same problem with "aws s3" on fedora cloud 39.

**Comment by tim-finnigan** [comment] 2023-12-04 22:54
Thanks for reaching out. @chris-palmer99 could you share your debug logs as well (with sensitive info redacted) and steps to reproduce?

@BowlesCR did this issue start occurring after updating to a specific version? You can refer to the [CHANGELOG](https://github.com/boto/botocore/blob/develop/CHANGELOG.rst?plain=1) for notes on what changes were introduced in which version. Can you reproduce the issue in environments other than that EC2 instance?

Does the error occur consistently or intermittently? And does it occur across services? If anyone can provide more detailed steps for reproducing this issue, that will help us to investigate further.

**Comment by tim-finnigan** [comment] 2023-12-04 23:07
A couple of other things to investigate: This issue may be related to `datetime` [changes](https://docs.python.org/3/whatsnew/3.12.html) in Python 3.12, so it would be good to test this in an environment with an earlier supported like Python 3.11. Also are you using anything third-party service such as `aws-vault` or `kiam` to get credentials?

**Comment by chris-palmer99** [comment] 2023-12-05 09:07
After a little more investigation I also raised this as a Fedora bug against awscli2, since that is where it is manifesting itself. That has more information including the stacktrace and reproducer steps. Note that for the reproducer, the contents of the IAM policy are rather irrelevant, as the failure occurs fetching the policy rather than applying it.

[https://bugzilla.redhat.com/show_bug.cgi?id=2252782](url)

**Comment by tim-finnigan** [comment] 2023-12-05 19:03
Thanks @chris-palmer99 for following up. Can you test this using Python 3.11 on FC39? That could help rule out whether this is an issue with the Fedora version or Python version (and how Python 3.12 handles `datetime`).

**Comment by BowlesCR** [comment] 2023-12-05 20:51
I wasn't tracking specific versions, but this started when I moved my deploy from F38 to F39 -- of course there's a whole laundry list of changes there.

No special tools managing the creds -- just using boto's ability to fetch the EC2 instance role via the instance metadata endpoint. That much seems to be working fine, its just choking on the date compare while defensively checking that the creds it got aren't already expired somehow.

I just wrote a test script on the same box that was problematic -- calling boto3 directly from a Python script instead of the awscli wrapper succeeds. F39, Python 3.12.0, boto + botocore 1.33.7 (fun version number) -- so that rules out Python 3.12 itself.


I'm leaning harder into the suspicion of a distro packaging issue -- the Fedora awscli2 package appears to be bundling botocore 2.0.0dev155 (the latest from https://github.com/boto/botocore/tree/v2) which was probably not ready for production use and hasn't been touched in 2 years. This has been the case since at least [awscli2-2.11.17-1.fc38.noarch.rpm](https://koji.fedoraproject.org/koji/buildinfo?buildID=2196536) released in May -- I stopped digging at the earliest version I could find for FC38. Likely date handling has been patched in master/develop (#3003 -- and maybe another one I'm missing because #3004 reverts that) but never backported to the v2 branch.

**Comment by tim-finnigan** [comment] 2023-12-22 20:14
Hi all - it looks like there have been some updates in the Fedora issue that was opened: https://bugzilla.redhat.com/show_bug.cgi?id=2252782. Can anyone confirm if this issue is resolved now?

**Comment by chris-palmer99** [comment] 2023-12-28 11:30
> Hi all - it looks like there have been some updates in the Fedora issue that was opened: https://bugzilla.redhat.com/show_bug.cgi?id=2252782. Can anyone confirm if this issue is resolved now?

I can confirm this was resolved in Fedora with awscli2.noarch 2.15.1-1.fc39 on 20 Dec. 
It also continues to work with awscli2-2.15.2-1.fc39.noarch which has just been pushed to updates.

**Comment by BowlesCR** [comment] 2023-12-29 11:59
Working great here too.
Thanks for the triage, and tracking the issue even though it ended up being elsewhere.

**Comment by tim-finnigan** [comment] 2024-01-02 20:18
Thanks for letting us know! Glad it's working now. I'll go ahead and close this issue.

**Closed by tim-finnigan** 2024-01-02 20:18 UTC
Labels: bug
