### ISSUE TITLE
Allow refreshing credentials from shared credentials file if file is modified

### ISSUE THREAD

**Issue by reegnz** [boto/botocore#2450] opened 2021-08-02 16:41 UTC
**Is your feature request related to a problem? Please describe.**
I am using cli toolling that generates shared credential files to refresh user credentials. These tools cannot be used for credential_process out of the box, but would have to be wrapped (and an expiry timestamp added as well).

**Describe the solution you'd like**
It would be nice for boto3 (and other AWS SDK-s as well) to notice if the shared credential file changes instead so changes to the file are automatically picked up without having to shell out to a credential process, or having to restart the process using the SDK.

**Comment by kdaily** [comment] 2021-08-03 21:23
Hi @reegnz,

Thanks for opening. This is a duplicate of this issue:

https://github.com/boto/botocore/issues/704

This is by design and is not recommended. You can refer to this comment for an example of how to add your own refreshable credential to the provider chain instead of using `credential_process`. 

https://github.com/boto/botocore/issues/704#issuecomment-151943324

That issue is still open so I'm going to close this and follow up on it there too. Thanks!

**Closed** 2021-08-03 21:26 UTC
Labels: credentials, duplicate, feature-request
