### ISSUE TITLE
better/real changelogs on api changes

### ISSUE THREAD

**Issue by kapilt** [boto/botocore#1908] opened 2019-12-08 18:19 UTC
I was perusing over some of the other sdk changes logs
https://github.com/aws/aws-sdk-go/blob/master/CHANGELOG.md
https://github.com/aws/aws-sdk-js/blob/master/CHANGELOG.md

and noticed they actually included real content, where as boto's typically consists of repeating
- updated service x client to latest version

ie
https://github.com/boto/boto3/blob/develop/CHANGELOG.rst
https://github.com/boto/botocore/blob/develop/CHANGELOG.rst

ideally the boto3/botocore .changes aggregation and changelog would include the service team's semantic/human message around the changes like every other sdk.

**Comment by swetashre** [comment] 2019-12-12 20:43
@kapilt - Let's track this issue under the linked boto3 issue. I am closing the issue as a duplicate of issue [#2230](https://github.com/boto/boto3/issues/2230).

**Closed** 2019-12-12 20:43 UTC
Labels: duplicate
