### ISSUE TITLE
Botocore 1.12.26 not available through pip

### ISSUE THREAD

**Issue by regan-karlewicz** [boto/botocore#1582] opened 2018-10-17 22:07 UTC
I'm trying to install boto3 @ 1.7.54 via pip. It's failing when downloading the botocore dependency @ version 1.12.26 saying that it doesn't exist. Looking at PyPI it seems that the botocore library's most recent version is 1.12.25, so it's failing to resolve the version required by boto3.

**Comment by jasonaowen** [comment] 2018-10-17 22:12
Duplicate of #1581

**Closed** 2018-10-17 22:16 UTC
