### ISSUE TITLE
Missing waiter for Firehose

### ISSUE THREAD

**Issue by gileadblucas** [boto/botocore#2483] opened 2021-09-13 16:11 UTC
**Describe the bug**
The documentation for [Firehose](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/firehose.html) does not include any `Waiter` instances, however the service does include a [get_waiter()](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/firehose.html#Firehose.Client.get_waiter) method.  The inclusion of this method is misleading.  One may assume that Firehose supports the use of `Waiter`s when, in fact, it does not.

**Steps to reproduce**
- Navigate to the [Firehose](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/firehose.html) documentation
- Note the existence of [get_waiter()](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/firehose.html#Firehose.Client.get_waiter) 
- Even though the method above exists, Firehose does not have any `Waiter`s to make use of. 

**Expected behavior**
The documentation is clear.  Either indicate that although the `get_waiters` method exist, there is no support for `Waiters` on Firehose.  Alternatively, add Firehose Waiters which can be used. 

**Debug logs**
N/A

**Comment by kdaily** [comment] 2021-09-13 19:36
Hi @gileadblucas,

Thanks for your post!

The `get_waiters` function is part of the base client class, so all AWS service clients have them. The documentation for waiters does state what happens when a service doesn't have any waiters defined:

> Using clients, you can learn the name of each waiter that a client has access to....Note if a client does not have any waiters, it will return an empty list when accessing its waiter_names attribute

https://boto3.amazonaws.com/v1/documentation/api/latest/guide/clients.html#waiters

Under the `get_waiter` documentation there is this:

>    **waiter_name** (*str*) -- The name of the waiter to get. See the waiters section of the service docs for a list of available waiters.

The 'waiters section of the service docs' refers to the page page [you referenced](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/firehose.html); if there were waiters, there would be a section for them. For example, see the [CloudWatch](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/cloudwatch.html) waiters list:

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/cloudwatch.html#waiters

Waiters are defined separately from a model file and dynamically loaded. There isn't anything to change here for the behavior as it's working as intended.

I could agree that the description of where to see the waiter definitions for this client is a bit confusing. Would a documentation change improve that experience?

**Comment by gileadblucas** [comment] 2021-09-14 15:53
Hi @kdaily,

Thank you for the quick and very informative response!

> The get_waiters function is part of the base client class, so all AWS service clients have them. 

Thanks for pointing this out, it makes much more sense as to why the Firehose service client has this function now.

> The documentation for waiters does state what happens when a service doesn't have any waiters defined:
>
> Using clients, you can learn the name of each waiter that a client has access to....Note if a client does not have any waiters, it will return an empty list when accessing its waiter_names attribute
>
> https://boto3.amazonaws.com/v1/documentation/api/latest/guide/clients.html#waiters

This is a key piece of information I wasn't aware of.  If I had known, my experience would have been smoother.

> I could agree that the description of where to see the waiter definitions for this client is a bit confusing. Would a documentation change improve that experience?

This is the key point of the issue.  I don't think the documentation of the function `get_waiters` is clear enough.  Maybe the docs for each service client could always include the "Waiters" section, and if that service does not support Waiters, there is a sentence to that effect.

Additionally `get_waiters()` function could be improved by including information, or a link to, the `waiter_names` attribute

Thanks again for the very helpful response.

**Comment by kdaily** [comment] 2021-09-14 16:32
Thanks for the feedback, @gileadblucas! I'll mark this as a potential improvement for the documentation.

**Comment by kdaily** [comment] 2021-09-15 19:31
We agree that adding an empty 'Waiters' section to client documentation pages would be the most clear. Thanks for that suggestion!

**Comment by kdaily** [comment] 2021-09-17 18:39
I'm going to open a new issue to track adding this, since it will clarify the request.

@gileadblucas, are there specific waiters you would like to be added? These are handled by the service team (Firehose), but I can bring awareness for waiters for specific operations. Thanks!

**Comment by gileadblucas** [comment] 2021-09-20 14:09
Hi @kdaily,

> are there specific waiters you would like to be added?
In my use case, I wanted to wait for a Firehose `DeliveryStream`'s to be `ACTIVE` before proceeding with my business logic.

**Comment by kdaily** [comment] 2021-09-20 22:33
Thanks @gileadblucas, agree that the section should indicate there are no waiters available.

I opened a separate issue (https://github.com/aws/aws-sdk/issues/126) to track that request.

**Comment by kdaily** [comment] 2021-09-20 22:34
Closing this as other issues have been opened to track the separate requests. Thanks again!

**Closed by kdaily** 2021-09-20 22:34 UTC
Labels: feature-request, documentation
