### ISSUE TITLE
datetime.datetime.utcnow() is deprecated as of Python 3.12

### ISSUE THREAD

**Issue by eduardo-boutiquenumerique** [boto/botocore#3201] opened 2024-06-09 09:23 UTC
### Describe the bug

The module botocore.auth.py uses the function datetime.datetime.utcnow() which is depreacated and throws the DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).

### Expected Behavior

The warning should not be raised

### Current Behavior

The DeprecationWarning is being raised

### Reproduction Steps

Using last versions botocore and launching python with options -Wa raises the warning

### Possible Solution

Replace datetime.datetime.utcnow() with datetime.datetime.now(datetime.UTC) as described in the warning itself

### SDK version used

1.34.122

### Environment details (OS name and version, etc.)

linux, ubunut

**Comment by tim-finnigan** [comment] 2024-06-11 17:38
This is a duplicate of https://github.com/boto/boto3/issues/3889. As mentioned there:
>The team is aware of this issue and working on addressing the warnings. These deprecations won't cause impact currently beyond the warnings. The required changes are not fully backwards compatible for existing usage. We'll be prioritizing a more robust fix in an upcoming release.

Closing to continue tracking in that issue.

**Closed by tim-finnigan** 2024-06-11 17:38 UTC
Labels: bug, investigating, needs-triage

**Comment by nguyenquocanhz** [comment] 2026-07-08 15:05
Tks Issues
