### ISSUE TITLE
Clarify multithreading documentation

### ISSUE THREAD

**Issue by dfee** [boto/botocore#1246] opened 2017-07-18 21:54 UTC
The [documentation for `boto3`](http://boto3.readthedocs.io/en/latest/guide/resources.html?highlight=multithreading#multithreading-multiprocessing) states that:
> It is recommended to create a **resource instance for each thread** / process in a multithreaded or multiprocess application rather than sharing a single instance among the threads / processes.(emphasis mine)

The documentation than goes on to show a code example where a `session` is created per thread, not a `resource`.

Reading through previous github issues, I see a [note](https://github.com/boto/botocore/issues/895#issuecomment-216972651) that we should create a separate session per thread. The comment that immediately follows says "resource", however.

So, do we need one session per thread, or are sessions thread safe, but not resources? Is there a 1:1 mapping between the thread safety of a `resource` and a `client`?

As a bonus question, how expensive / wasteful is it to create new clients (or sessions, as above) on-demand per executor thread...?

**Comment by JordonPhillips** [comment] 2017-07-19 17:05
Thanks for the feedback! I agree that it's a little ambiguous, we'll make sure to get that updated.

**Comment by dfee** [comment] 2017-07-25 23:09
In the meantime (before you update the documentation), can you provide some insight to those questions? Thanks :)

**Comment by joethompsonduo** [comment] 2018-03-07 20:04
An update is still needed.

**Comment by shadycuz** [comment] 2018-03-28 13:00
This ^

**Comment by joethompsonduo** [comment] 2018-03-28 13:11
Once again, echoing the sentiment that some sort of response is needed. Can you acknowledge that the maintainers are at least receiving these communications?

**Comment by jweinst1** [comment] 2018-05-07 23:54
Question, for firing large amounts of s3 restore_object requests, across multiple threads, what is the safest approach to take?

**Comment by tuukkamustonen** [comment] 2018-06-05 07:15
Also wondering how this is. I've been carelessly sharing session and client instances over threads for years without (perceived) problems. Not saying it's the way to go, but I wonder what are the cases where it might break?

**Comment by rahulr3** [comment] 2018-06-23 07:17
Can someone comment ? I'm working on a multithreaded application and each thread is creating it's own session/ resource. Are sessions/resource thread safe ? How expensive it is to create session, resource, clients at scale ?

**Comment by zoresvit** [comment] 2018-09-28 00:54
@JordonPhillips 

Guys, it's really not cool to promise the update, but then *completely ignore* the issue, the update and all the questions for more than a year.

**Comment by lhufnagel** [comment] 2018-10-08 06:51
Am I right in assuming, that with the switch to urllib3 ([which promises thread-safety](https://urllib3.readthedocs.io/en/latest/)) in [botocore 1.11.0](https://botocore.amazonaws.com/v1/documentation/api/latest/index.html#upgrading-to-1-11-0) we should be good?

**Comment by NickWoodhams** [comment] 2018-11-27 05:41
I would also like some insight on this. I have been using put_object in celery workers and getting intermittent errors and I cannot figure out if this is due to the number of concurrent workers and limitations from AWS as to the number of clients, or an issue of threading within Boto. 

Could someone please provide some insight? I would be very grateful.

**Comment by ori-n** [comment] 2018-12-04 07:05
Could someone please share a code example for working with a session per thread? Thanks

**Comment by hajapy** [comment] 2019-08-07 00:28
I would echo that this remains an issue. Clearer documentation would be helpful, as would general thread safety in the construction of clients/resources/sessions.

**Comment by nebi-frame** [comment] 2020-02-13 14:45
I have no idea why no one from AWS gives a clear explanation for all these issues raised.

**Comment by LyleScott** [comment] 2020-02-22 02:42
Instead of 

```
import boto3
s3 = boto3.resource("s3")
s3.Object(bucket_name, filename).put(Body=s.getvalue())
```

I used

```
import boto3.session
sess = boto3.session.Session()
c = sess.client("s3")
c.put_object(Bucket=bucket_name, Key=filename, Body=s.getvalue())
```

and then multithreading worked fine.

**Comment by rohan-mo** [comment] 2020-03-04 08:39
@JordonPhillips I've just seen this documentation and it is still vague as was originally pointed out by the issue author. 
Could you please help clarify the documentation here?

**Comment by Luis-Palacios** [comment] 2020-05-08 18:59
I'm joining the party here, I need to query from different regions depending on certain parameters on each request and just realized initializing a boto3 resource is not exactly cheap so planning on initialization a resource for each possible region on app start as a singleton and then using the corresponding resource.

I started thinking about thread-safe, I went to docs and I was not able to understand if this is going to be thread-safe.

I will highly appreciate clarifications too

**Comment by jsmodic** [comment] 2020-05-16 02:58
I've fought with this issue a few times due to adverse effects of role based authentication and multiple botocore sessions.

From reading the code alone, it's clear there are thread safety problems. [This initialization pattern](https://github.com/boto/botocore/blob/develop/botocore/session.py#L916) combined with [how it lazy initializes things](https://github.com/boto/botocore/blob/develop/botocore/session.py#L152) and then [how it creates clients](https://github.com/boto/botocore/blob/develop/botocore/session.py#L805) is definitely not thread safe, and that's just something that immediately stands out.

However, if you [look at other parts](https://github.com/boto/botocore/blob/develop/botocore/credentials.py#L480), it's obvious there is careful consideration to thread safety.

So it really looks like it is supposed to be thread safe but isn't in practice.

**Comment by rohan-mo** [comment] 2020-05-18 11:23
@jsmodic If you have the time, could you please explain the links and _why_ those code snippets are not thread safe.

**Comment by jsmodic** [comment] 2020-05-18 17:02
The shared state. See the error this guy gets [on SO](https://stackoverflow.com/a/57725458). That dictionary is not protected in any way

Also at one point they seemingly attempt to [fix that](https://github.com/boto/botocore/pull/1033) but seemingly have rolled it back since then.

**Comment by mattsb42-aws** [comment] 2020-05-18 21:49
This is called out in the boto3 docs[1], but it could be more visible. What is not clear in those docs is whether botocore sessions have the same issue or if using a common botocore session across multiple boto3 sessions is sufficient.

[1] https://boto3.amazonaws.com/v1/documentation/api/latest/guide/resources.html#multithreading-multiprocessing

**Comment by rohan-mo** [comment] 2020-05-21 12:17
@mattsb42-aws @thomas-barton I don't think this issue should be closed yet. 

The change clarifies the documentation, but as pointed out in [this](https://github.com/boto/botocore/issues/1246#issuecomment-629578498) comment above, `botocore.session.Session` isn't thread-safe (maybe, this can also be confirmed by the aws team). And since `boto3.session.Session` internally initializes a `botocore.session.Session`, is it actually thread-safe? I mean, does it implement some work around to make the internally used `botocore.session.Session` thread-safe or is it susceptible to the same issues as `botocore.session.Session`?

**Comment by jsmodic** [comment] 2020-05-22 02:32
boto3 defers directly to the botocore session and [doesn't do anything special](https://github.com/boto/boto3/blob/develop/boto3/session.py#L258). Creating a client in threads is not threadsafe. You can test that one pretty easily with some quick code:

```
from concurrent.futures import ThreadPoolExecutor
import boto3

def test_session(boto3_session):
    boto3.client("s3")
    return "Got a client"

with ThreadPoolExecutor(max_workers=20) as executor:
    boto3_session = boto3.Session()
    futures = []
    for _ in range(100):
        futures.append(executor.submit(test_session, boto3_session))
    for future in futures:
        print(future.result())
```

You'll get it to fail easily in that block I posted above from the botocore session:

```
Traceback (most recent call last):
  ....
  File "/.../python3.6/site-packages/botocore/session.py", line 923, in get_component
    del self._deferred[name]
KeyError: 'credential_provider'
```

**Comment by pedros007** [comment] 2020-05-26 22:53
I also ran into problems with multithreading client creation. My use case was a bunch of `head_object` requests to see if `n` different keys exist in a bucket.

Here's something which seems to work: In the main thread, create a client with a config using a number for `max_pool_connections`. Use the client by all the child threads. Make sure `max_pool_connections` is the number of threads you launch.  Here's a snippet where I call some `my_head_object_function(key, client)` which returns `True` if the object exists at the given key using the given client.

```python
    num_threads = 16
    cfg = botocore.config.Config(max_pool_connections=num_threads)
    client = boto3.client("s3", config=cfg)
    futures = {}
    with ThreadPoolExecutor(max_workers = num_threads) as executor:
        for key in keys:
            f = executor.submit(my_head_object_function, key, client)
            futures[f] = key
    # ... process the results of the futures as_completed
```

**Comment by flyingdev** [comment] 2020-06-03 18:09
@jsmodic I had similar issue recently and need to create session per each thread.
And this is what boto3 documentation recommends.
```
    class MyTask(threading.Thread):
        def run(self):
            session = boto3.session.Session()
            s3 = session.resource('s3')
```

Slight updated.
```
from concurrent.futures import ThreadPoolExecutor
import boto3

def test_session():
    session = boto3.Session()
    session.client("s3")

    return "Got a client"

with ThreadPoolExecutor(max_workers=20) as executor:
    futures = []
    for _ in range(100):
        futures.append(executor.submit(test_session))
    for future in futures:
        print(future.result())
```

So create session in test_session.

Thank you.

**Comment by jsmodic** [comment] 2020-06-03 18:17
@flyingdev yes you can do that, but you need to be careful when creating sessions depending on your use case. For example, creating a new session will reauthenticate, and if you're using role based auth on EC2, aws can start throttling / failing your authentication from too many IAM calls if you're aggressively creating sessions.

**Comment by dash-samuel** [comment] 2020-09-22 10:31
Hi everyone in my case I can successfully create multiple threads that share the same session, and am able to download from an S3 bucket for example without problems. 

This is how I do it:

```python
import concurrent.futures
import boto3
import json

# setup client and session
sess = boto3.session.Session()
client = sess.client("s3")

files = ["path-to-file.json", "path-to-file2.json"] 

def download_from_s3(file_path):
    obj = client.get_object(Bucket="<your-bucket>", Key=file_path)
    resp = json.loads(obj["Body"].read())
    return resp

with concurrent.futures.ThreadPoolExecutor() as executor:
     executor.map(download_from_s3, files)

```

**Comment by tomaszhlawiczka** [comment] 2021-01-13 09:24
The doc https://boto3.amazonaws.com/v1/documentation/api/latest/guide/resources.html#multithreading-and-multiprocessing states:
> It is recommended to create a resource instance for each thread / process in a multithreaded or multiprocess application rather than sharing a single instance among the threads / processes.

Then how can I benefit from reused connections with `max_pool_connections` → https://botocore.amazonaws.com/v1/documentation/api/latest/reference/config.html#botocore-config ?

**Comment by jmehnle** [comment] 2021-03-05 18:44
@dash-samuel wrote:
> Hi everyone in my case I can successfully create multiple threads that share the same session, and am able to download from an S3 bucket for example without problems.

Your threads are sharing the _client_, which is officially thread-safe. This explains why your example works, but this doesn't mean you can *generally* share a session across threads. Directly operating (such as _creating_ clients) on a shared session from multiple threads, is _not_ thread-safe, as the example in https://boto3.amazonaws.com/v1/documentation/api/latest/guide/resources.html#multithreading-and-multiprocessing implies.

**Comment by ryansonshine** [comment] 2021-05-05 20:04
To summarize, there are two cases, one being multithreading and the other being multiprocessing.

**Session**: Unsafe in all cases due to shared metadata/urllib3.

**Resource:** Unsafe in all cases due to its direct interaction with a Botocore session.

**Client**: (Assuming the client is not used to interact with the underlying Botocore Session) Safe in a threaded environment, unsafe in a multiprocess environment. This is due to forking issues with urllib3’s connection pool and leaves botocore unable to guarantee http messages are read in the right order if the pool isn’t created under the same PID. (https://github.com/psf/requests/issues/4323)

I've opened up a PR https://github.com/boto/boto3/pull/2848 and am requesting feedback if this makes it more clear.

**Comment by nateprewitt** [comment] 2021-05-19 17:46
We've merged #2848 today, adding detailed information on multi-threading requirements for each of the main Botocore primitives (Clients, Resources and Sessions).  The updated documentation should be in the next release. I'll leave this open until the end of the week for any further feedback and we'll plan to resolve afterwards. Thanks everyone!

**Closed** 2021-05-21 18:54 UTC
Labels: documentation, enhancement

**Comment by blakete** [comment] 2023-10-25 19:29
> To summarize, there are two cases, one being multithreading and the other being multiprocessing.
> 
> **Session**: Unsafe in all cases due to shared metadata/urllib3.
> 
> **Resource:** Unsafe in all cases due to its direct interaction with a Botocore session.
> 
> **Client**: (Assuming the client is not used to interact with the underlying Botocore Session) Safe in a threaded environment, unsafe in a multiprocess environment. This is due to forking issues with urllib3’s connection pool and leaves botocore unable to guarantee http messages are read in the right order if the pool isn’t created under the same PID. ([psf/requests#4323](https://github.com/psf/requests/issues/4323))
> 
> I've opened up a PR [boto/boto3#2848](https://github.com/boto/boto3/pull/2848) and am requesting feedback if this makes it more clear.

@ryansonshine is comment still up to date? My main take away is that clients are thread safe while sessions and resources are not.

**Comment by ryansonshine** [comment] 2023-10-25 19:59
> > To summarize, there are two cases, one being multithreading and the other being multiprocessing.
> > **Session**: Unsafe in all cases due to shared metadata/urllib3.
> > **Resource:** Unsafe in all cases due to its direct interaction with a Botocore session.
> > **Client**: (Assuming the client is not used to interact with the underlying Botocore Session) Safe in a threaded environment, unsafe in a multiprocess environment. This is due to forking issues with urllib3’s connection pool and leaves botocore unable to guarantee http messages are read in the right order if the pool isn’t created under the same PID. ([psf/requests#4323](https://github.com/psf/requests/issues/4323))
> > I've opened up a PR [boto/boto3#2848](https://github.com/boto/boto3/pull/2848) and am requesting feedback if this makes it more clear.
> 
> @ryansonshine is comment still up to date? My main take away is that clients are thread safe while sessions and resources are not.

Hi @blakete , the information merged on PR https://github.com/boto/boto3/pull/2848 is up to date.

**Comment by anteph** [comment] 2024-02-08 15:04
Hi @ryansonshine , sorry to revive this old thread :) 

I was reading the generic problem with sharing a boto3 client with multiple processes. It is my understanding that it is related to the urllib3 connection pool that boto uses under the hood, which is problematic if shared amongst processes.

I was going through one of the linked issues (https://github.com/psf/requests/issues/4323) and this caught my attention:
>  It can’t happen merely by creating a Session before forking, it has to actually be used before the fork.


I'm no expert on the lower level details of what a fork does, but I believe in Unix it uses a copy on write approach, meaning that it copies the parent process memory only when it effectively intends to modify it. However, this doesn't work for neither sockets or opened files (meaning that they are not fork safe).

So, my expectation is that it would be ok if the connection pool was initialized in the parent process and then used by the child processes because they would eventually get a copy, as long as the connection pool was never used in the parent process (thus, no socket created prior to fork).

Translating this a layer up to Boto, my expectation would be that it is safe to initialize a boto3 client (creating the object) in the parent process and have the child processes using that instance (eventually it will get copied), as long as there was never any operation being performed prior to the fork.

The reason I'm asking this is because of the use case Celery + Boto with Celery using fork to spawn workers. 
I'm was basically planning to initialize the boto3 client prior to the fork and use it for operations only after. 
The reason for doing this is because celery does import app modules in the master process and only then does the fork: https://github.com/celery/celery/issues/6036. This means that any global variables we declare are evaluated still in the master process. 

Do you think this would be safe or am I making incorrect assumptions? I'm also not sure if the initialization of the boto3 client itself is somehow doing some network call that could be already filling the conn pool, so this may eventually be dangerous anyway?

I can always work this around with a lazy initialization of the object, but before doing so wanted to be sure it is really necessary.

Thanks :)
