### ISSUE TITLE
Stubber not intercepting

### ISSUE THREAD

**Issue by mcaulifn** [boto/botocore#1799] opened 2019-08-01 20:08 UTC
When using a client created outside of the test, calls are made to an actual client.
Given the following code and tests:
```python
def create_client(service):
    return boto3.client(service, config=CLIENT_CONFIG)

def get_security_group_data(filters):
    client = create_client('ec2')
    return client.describe_security_groups(Filters=filters)

def test_get_security_group_data():
    import boto3
    from botocore.stub import Stubber
    ec2_client = boto3.client('ec2', region_name='us-west-2')
    filters = [
            {
                'FilterName': 'tag:Name',
                'FilterValues': [
                    'Default'
                ]
            }
        ]

        describe_security_groups_response = {
            'SecurityGroups': [
                {
                    'GroupName': 'Default',
                    'GroupId': 'sg-1234abc',
                    'VpcId': 'vpc-12345ab',
                    'Tags': [
                        {
                            'Key': 'Name',
                            'Value': 'Default'
                        },
                    ],
                }
            ]
        }
    stubber = Stubber(ec2_client)
    stubber.add_response('describe_security_groups', describe_security_groups_response,
                         {'Filters': filters})
    stubber.activate()
    response_data = get_security_group_data(filters)
```
The following is raised during the test:
```
security_group.py:18: in get_security_group_data
    client = create_client('ec2')
functions.py:7: in create_client
    return boto3.client(service, config=CLIENT_CONFIG)
.env/lib/python3.7/site-packages/boto3/__init__.py:91: in client
    return _get_default_session().client(*args, **kwargs)
.env/lib/python3.7/site-packages/boto3/session.py:263: in client
    aws_session_token=aws_session_token, config=config)
.env/lib/python3.7/site-packages/botocore/session.py:839: in create_client
    client_config=config, api_version=api_version)
.env/lib/python3.7/site-packages/botocore/client.py:86: in create_client
    verify, credentials, scoped_config, client_config, endpoint_bridge)
.env/lib/python3.7/site-packages/botocore/client.py:328: in _get_client_args
    verify, credentials, scoped_config, client_config, endpoint_bridge)
.env/lib/python3.7/site-packages/botocore/args.py:47: in get_client_args
    endpoint_url, is_secure, scoped_config)
.env/lib/python3.7/site-packages/botocore/args.py:117: in compute_client_args
    service_name, region_name, endpoint_url, is_secure)
.env/lib/python3.7/site-packages/botocore/client.py:402: in resolve
    service_name, region_name)
.env/lib/python3.7/site-packages/botocore/regions.py:122: in construct_endpoint
    partition, service_name, region_name)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <botocore.regions.EndpointResolver object at 0x7ff86a4c9208>
partition = OrderedDict([('defaults', OrderedDict([('hostname', '{service}.{region}.{dnsSuffix}'), ('protocols', ['https']), ('sig...1', OrderedDict()), ('us-east-2', OrderedDict()), ('us-west-1', OrderedDict()), ('us-west-2', OrderedDict())]))]))]))])
service_name = 'ec2', region_name = None

    def _endpoint_for_partition(self, partition, service_name, region_name):
        # Get the service from the partition, or an empty template.
        service_data = partition['services'].get(
            service_name, DEFAULT_SERVICE_DATA)
        # Use the partition endpoint if no region is supplied.
        if region_name is None:
            if 'partitionEndpoint' in service_data:
                region_name = service_data['partitionEndpoint']
            else:
>               raise NoRegionError()
E               botocore.exceptions.NoRegionError: You must specify a region.

.env/lib/python3.7/site-packages/botocore/regions.py:135: NoRegionError
------------------------------------------------------------ Captured log call ------------------------------------------------------------
INFO     botocore.credentials:credentials.py:1093 Found credentials in shared credentials file: ~/.aws/credentials
```

**Comment by swetashre** [comment] 2019-08-02 19:44
@mcaulifn - Thank you for your post. It looks like the cause of this is that the client is being re-defined after the Stubber is applied, and it's trying to hit the API for real. Here is a sample code i used to make it work : 
```python
def get_security_group_data(filters,ec2client):
    return ec2client.describe_security_groups(Filters=filters)

def test_get_security_group_data():
    import boto3
    from botocore.stub import Stubber
    ec2_client = boto3.client('ec2',region_name='us-west-2')
    filters = [
            {
                'Name': 'tag:Name',
                'Values': [
                    'Default'
                ]
            }
        ]

    describe_security_groups_response = {'SecurityGroups': [ { 'GroupName': 'Default','GroupId': 'sg-1234abc','VpcId': 'vpc-12345ab',}]}
                
    stubber = Stubber(ec2_client)
    stubber.add_response('describe_security_groups', describe_security_groups_response,
                         {'Filters': filters})
    stubber.activate()
    response_data = get_security_group_data(filters,ec2client=ec2_client)
```
You can do like this or you can directly call the ```describe_security_group``` inside test_get_security_group_data() function instead of defining another function for that 

```python
def test_get_security_group_data():
    import boto3
    from botocore.stub import Stubber
    ec2_client = boto3.client('ec2',region_name='us-west-2')
    filters = [
            {
                'Name': 'tag:Name',
                'Values': [
                    'Default'
                ]
            }
        ]

    describe_security_groups_response = {'SecurityGroups': [ { 'GroupName': 'Default','GroupId': 'sg-1234abc','VpcId': 'vpc-12345ab',}]}
                
    stubber = Stubber(ec2_client)
    stubber.add_response('describe_security_groups', describe_security_groups_response,
                         {'Filters': filters})
    stubber.activate()
    response_data = ec2_client.describe_security_groups(Filters=filters)
```
Hope it helps and please let me know if you have any questions.

**Comment by mcaulifn** [comment] 2019-08-05 11:31
@swetashre I am able to run the test if I pass in the stub client to the function that uses the client.

How can tests be run where the client is created within the function? Something like the `mock.patch` decorator?

**Comment by swetashre** [comment] 2019-08-14 22:33
I am not able to understand what do you mean by ```tests be run where the client is created within the function```. Can you please give me some more information on what you want to do with ```mock.patch``` decorator ?

**Comment by mcaulifn** [comment] 2019-08-20 17:23
In my original example, attempting to test `get_security_group_data` fails as the client is defined and then used within that function. The decorator could be used similar to how `mock.patch` is used.

```python
@mock.patch('boto3.client')
def test_get_security_group_data(mocked_client):
    #
    filters = [
        {
            'Name': 'tag:Name',
            'Values': [
                'Default'
            ]
        }
    ]

    mocked_response = {
        'SecurityGroups': [
            {
                'GroupName': 'Default',
                'GroupId': 'sg-1234abc',
                'VpcId': 'vpc-12345ab',
                'Tags': [
                    {
                        'Name': 'Name',
                        'Value': 'Default'
                    },
                ],
            }
        ]
    }

    mocked_client.describe_security_groups.return_value = mocked_response

    #
    security_group_data = ec2.get_security_group_data(mocked_client, filters)
```

**Comment by swetashre** [comment] 2019-08-20 18:13
@mcaulifn - Thank you for the reply. Yes, you can use mock.patch instead of stubber . But in both the case you have to either pass the mocked_client or stubbed_client to the ```get_security_group_data``` function otherwise it will make a original api call. 

This is a link of stackoverflow thread which explains how you can use both stubber and mock.patch 
https://stackoverflow.com/questions/37143597/mocking-boto3-s3-client-method-python

Please let me know if you have any questions.

**Comment by mcaulifn** [comment] 2019-08-20 19:15
I think you are talking about this: https://stackoverflow.com/a/56263494/7705373 ?

I was looking for a cleaner solution using only botocore, suggesting a decorator that would handle patching the client created in the function being tested.

**Comment by swetashre** [comment] 2019-08-20 19:26
@mcaulifn - The code you provided will work with mock.patch and if you want to use stubber then you can use the code i provided earlier. 

Code snippet for mock.patch:
```python
import boto3
from mock import patch

@mock.patch('boto3.client')
def test_get_security_group_data1(mocked_client):
    filters = [
        {
            'Name': 'tag:Name',
            'Values': [
                'Default'
            ]
        }
    ]

    mocked_response = {
        'SecurityGroups': [
            {
                'GroupName': 'Default',
                'GroupId': 'sg-1234abc',
                'VpcId': 'vpc-12345ab',
                'Tags': [
                    {
                        'Name': 'Name',
                        'Value': 'Default'
                    },
                ],
            }
        ]
    }
    mocked_client.describe_security_groups.return_value = mocked_response

    response = mocked_client.get_security_group_data(mocked_client, filters)


def get_security_group_data(mocked_client,filters):
    return mocked_client.describe_security_groups(Filters=filters)
```
This code will work for mock.patch. Please let me know if you are looking for something else.

**Comment by mcaulifn** [comment] 2019-08-29 13:00
@swetashre the link you provided is unclear. The top solution does not show the client being patched.  I still don't know which piece of code you are referring to. Please post your working code on how to test using `botocore.Stubber` and patching the client being created outside of the test. 

The original ask was for a `botocore` decorator to be created to address patching and Stubber in order to simplify testing.

**Comment by nojohnny101** [comment] 2021-01-25 15:36
I am also having this problem.

I'm taking advantage of lambda layers to store all my clients in a setup.py file which all lambda functions can import from. As @mcaulifn described, when running test the stubber gets over written when the lambda function executes because the client is being imported in the lambda_function.

@mcaulifn  did you ever find a solution for this?

**Comment by mcaulifn** [comment] 2021-02-16 13:19
This is what I eventually came up with:

```python
@mock.patch.dict('os.environ', {'AWS_DEFAULT_REGION': 'us-west-2'})
@mock.patch('app.module.create_client')
def test_construct_and_publish_message(mocked_client):
    """Test construct_and_publish."""
    # Arrange
    event_dict = {
        'what': 'create',
        'app': 'app1',
        'version': '2',
        'status': 'success',
        'region': 'us-west-2'
    }

    expected_params = {
        'TopicArn': 'arn:aws:sns:us-west-2:12345678912:events',
        'Subject': 'create::final',
        'Message': mock.ANY
    }
    service = 'sns'
    sns_client = boto3.client(service)
    stubber = Stubber(sns_client)
    stubber.add_response('publish', {'MessageId': 'string', 'SequenceNumber': 'string'}, expected_params)
    stubber.activate()
    mocked_client.return_value = sns_client

    # Act
    construct_and_publish_message(**event_dict)

    # Assert
    mocked_client.assert_called_with(service)
    stubber.assert_no_pending_responses()
    stubber.deactivate()

**Comment by tim-finnigan** [comment] 2021-08-11 16:24
Hi @mcaulifn, thanks for following up on this issue. It looks like you came up with a working solution. 

Here is the botocore Stubber [documentation](https://botocore.amazonaws.com/v1/documentation/api/latest/reference/stubber.html) for more context on this topic, and here are some [code samples](https://docs.aws.amazon.com/code-samples/latest/catalog/python-test_tools-example_stubber.py.html) for testing various services using Stubber.

I’ll go ahead and close this issue. Please create a new issue if there’s anything else that you want to bring to our attention.

**Closed by tim-finnigan** 2021-08-11 16:24 UTC
Labels: guidance

**Comment by mcaulifn** [comment] 2021-08-16 13:52
@tim-finnigan The existing documentation is not very helpful as it shows code within a test file rather than in a module or package. Can you update the docs to show a better real world type example?

**Comment by tim-finnigan** [comment] 2021-08-16 16:52
Hi @mcaulifn, I can bring this up with our doc writers and see if there are better examples we could add. 

I saw you were using SNS in an earlier post. This other code samples page may provide more relevant examples for your use case: https://docs.aws.amazon.com/code-samples/latest/catalog/python-sns-test-test_sns_basics.py.html
