### ISSUE TITLE
_is_generic_error_response error on empty body

### ISSUE THREAD

**Issue by SeleniumK** [boto/botocore#1570] opened 2018-09-27 16:28 UTC
Occasionally (tracking down under what exact circumstances), s3 appears to be returning a 500+ error code with a None body.

In botocore.parsers._is_generic_error_response:

```
if response['status_code'] >= 500:
    body = response['body'].strip()
    return body.startswith(b'<html>') or not body
```
An attribute error is thrown

`AttributeError: 'NoneType' object has no attribute 'strip'`

Python Version -- 2.7
Botocore Version -- botocore==1.10.66
Running an alpine image (openresty)

I am encountering this through thumbor requests -- with tc_aws https://github.com/thumbor-community/aws/tree/master/tc_aws

**Comment by joguSD** [comment] 2018-10-09 17:37
@SeleniumK Did you ever manage to track down what triggers this behavior?

**Comment by SeleniumK** [comment] 2018-10-09 22:07
This appears to be related to this particular behavior of thumbor https://github.com/thumbor/thumbor/issues/208

Everything in Tornado happens inside an event loop. When PIL is running, that event loop is blocked. When a big image is being resized, the event loop can't respond to events that happen. Here is what I think is happening:

Start downloading image A
Start downloading image B
Image A finished downloading. Start Processing image A (blocking IOLoop)
Image B finished downloading, but event can't be acknowledged since IOLoop is blocked
......
timeout with partially-downloaded image

I am pretty sure this is the behavior that prompts the None Body/Attribute error :)

**Comment by joguSD** [comment] 2018-10-11 21:17
Ah, that explains why I was unable to reproduce this. Thumbor uses [`tornado-botocore`](https://github.com/nanvel/tornado-botocore/blob/master/tornado_botocore/base.py) which completely bypasses our default HTTP layer for an async version. While our HTTP client seems to never return an `None` body we are making that assumption implicitly in parser code so I'm still inclined to accept the open PR.

**Comment by SeleniumK** [comment] 2018-10-11 21:19
That makes a ton of sense -- and also explains why I couldn't find other people who'd experienced much of that :)

**Comment by joguSD** [comment] 2018-10-12 00:40
Merged the related PR and the fix should go out tomorrow (10/12), if not It will go out on Monday (10/15).

**Closed by joguSD** 2018-10-12 00:40 UTC
Labels: investigating
