### ISSUE TITLE
No paginator for EC2 describe_addresses

### ISSUE THREAD

**Issue by lovepurohit** [boto/botocore#2056] opened 2020-05-22 08:10 UTC
**There is no paginator available for the describe addresses**
As paginator allows you to automatic paginate the resource,

**Add the paginator to the EC2 describe_addresses**
It is good to have the paginate functionality for all the list or describe resources as the number of response vary from account to account. It will increase the reliability of the responses from the API.

Thank you

**Comment by swetashre** [comment] 2020-05-26 21:45
@lovepurohit - This issue is a duplicate of issue https://github.com/boto/boto3/issues/2451. There is already a response to it. Let's track this issue under the linked github issue. Closing this issue as duplicate.

**Closed by swetashre** 2020-05-26 21:45 UTC
Labels: duplicate
