### ISSUE TITLE
Can't use s3 signature version with private S3 URL.

### ISSUE THREAD

**Issue by Andrey-mp** [boto/botocore#601] opened 2015-07-08 10:21 UTC
region = 'MyRegion'
    connection_data = {
        'config_file': (None, 'AWS_CONFIG_FILE', None, None),
        'region': ('region', 'BOTO_DEFAULT_REGION', region, None),
    }
    session = botocore.session.get_session(connection_data)
    config = botocore.client.Config(signature_version='s3')
    client = session.create_client(
        's3', region_name=region, endpoint_url='http://my_url:1234',
        aws_access_key_id='MyAccessKey', aws_secret_access_key='MySecret',
        config=config)
    client.get_object(Bucket='MyBucket', Key='MyKey')

I need to use 's3' signature version because my server doesn't support 's3v4' auth protocol.
So when I call get_object I get in logs - 'Starting new HTTP connection (1): bucket-944102956.s3.amazonaws.com'
So this request goes to amazon server - this is a bug.

**Comment by Andrey-mp** [comment] 2015-07-08 12:13
it substitutes another name here - https://github.com/boto/botocore/blob/develop/botocore/utils.py#L637

**Comment by mtdowling** [comment] 2015-07-10 19:40
I think we need to add the ability to disable the bucket hostname overrides with a custom parameter. This sort of behavior is present in other AWS SDKs, for example: https://github.com/aws/aws-sdk-php/blob/master/src/S3/S3Client.php#L33. Marking as a feature request.

**Comment by phoet** [comment] 2016-01-19 11:20
having the same issue, any estimates? is there something i can help with?

**Comment by JordonPhillips** [comment] 2016-01-22 23:55
I think the issue is with botocore trying to use path style addressing by default ([here](https://github.com/boto/botocore/blob/develop/botocore/utils.py#L645)). To get rid of that, you can remove `fix_s3_host` like so:

```python
import botocore.session
from botocore.utils import fix_s3_host

session = botocore.session.get_session()
client = session.create_client('s3')
client.meta.events.unregister('before-sign.s3', fix_s3_host)
```

**Comment by phoet** [comment] 2016-02-09 14:13
@JordonPhillips i tried what you suggested but i'm still getting the wrong url. in your example, where are you assuming to set the host/endpoint_url?

i tried this:

```python
        session = session_handler.get_session()
        client = session.create_client('s3', endpoint_url=self._private_host)
        client.meta.events.unregister('before-sign.s3', fix_s3_host)
        client.generate_presigned_url(...)
```

**Comment by kengruven** [comment] 2016-02-09 17:20
I'm not sure about `get_session()` versus `Session()`, but one thing that I discovered is that aws_access_key_id and aws_secret_access_key can't be None, but they can be bogus.  I'm doing something pretty similar to you, and it works for me with fake-s3:

    session = boto3.session.Session(aws_access_key_id='---', aws_secret_access_key='---')
    resource = session.resource('s3', endpoint_url=..., use_ssl=False)
    client = resource.meta.client
    client.meta.events.unregister('before-sign.s3', fix_s3_host)
    client.generate_presigned_url('get_object', Params={'Bucket": ..., 'Key': ...}, ExpiresIn=...)

Another trick I found is that if you specify `region_name="us-gov-west-1"` (one of botocore's `RESTRICTED_REGIONS`), then `fix_s3_host()` is a no-op.

**Comment by Andrey-mp** [comment] 2016-02-10 05:53
@kengruven if you specify region then signature v4 will be used. but we talk about usign signature v2.

**Comment by JordonPhillips** [comment] 2016-02-10 18:48
There is now a way to specify addressing style when you create a client, I updated my comment above. For your use @Andrey-mp, you would do something like this:

```python
import botocore.session
from botocore.client import Config

session = botocore.session.get_session()
config = Config(s3={'addressing_style': 'path'}, signature_version='s3')
client = session.create_client('s3', config=config)
```

Let me know if that works out

**Closed** 2016-03-01 23:52 UTC
Labels: question
