### ISSUE TITLE
ClientError: An error occurred (UnknownOperationException) when calling the ListSchemas operation:

### ISSUE THREAD

**Issue by chrisking** [boto/botocore#1846] opened 2019-10-13 15:00 UTC
It looks like there is a problem with the client.py file inside botocore, issue opened on Personalize's API here https://github.com/boto/botocore/issues/1844 . Also there's a corresponding issue on Forecast: https://github.com/aws-samples/amazon-forecast-samples/issues/38 

To reproduce this, generate a new Python3.7 or 3.6.5 environment and perform the following:

## Meta Information

```
(personalize) ➜  ~ pip freeze | grep boto
boto3==1.9.248
botocore==1.12.248
(personalize) ➜  ~ python --version
Python 3.7.3
```

## Steps to Reproduce Error:

1. Install versions of libraries listed above
2. Execute the following:

```
ipython
import boto3
personalize = boto3.client('personalize')
personalize.list_schemas()
```

## Output:

```
personalize.list_schemas()
---------------------------------------------------------------------------
ClientError                               Traceback (most recent call last)
<ipython-input-3-4bf9284f94ae> in <module>
----> 1 personalize.list_schemas()

~/personalize/lib/python3.7/site-packages/botocore/client.py in _api_call(self, *args, **kwargs)
    355                     "%s() only accepts keyword arguments." % py_operation_name)
    356             # The "self" in this scope is referring to the BaseClient.
--> 357             return self._make_api_call(operation_name, kwargs)
    358
    359         _api_call.__name__ = str(py_operation_name)

~/personalize/lib/python3.7/site-packages/botocore/client.py in _make_api_call(self, operation_name, api_params)
    659             error_code = parsed_response.get("Error", {}).get("Code")
    660             error_class = self.exceptions.from_code(error_code)
--> 661             raise error_class(parsed_response, operation_name)
    662         else:
    663             return parsed_response

ClientError: An error occurred (UnknownOperationException) when calling the ListSchemas operation:
```

**Comment by swetashre** [comment] 2019-10-15 17:48
@chrisking - This issue is same as issue #1844 opened in botocore and there is already a response to the issue. I am closing this issue as a duplicate of issue #1844

**Closed** 2019-10-15 17:49 UTC
Labels: duplicate
