### ISSUE TITLE
docutils version conflit with 0.15.1

### ISSUE THREAD

**Issue by laszewsk** [boto/botocore#1796] opened 2019-07-29 09:14 UTC
I am using docutils 0.15.1, however i get a version conflict as boto core requires another version:
Requirement.parse('docutils<0.15,>=0.10'), {'botocore'}) It would be great if you can update so it works also with the current version.

There seems also to be a discussion to remove docutils #900 and conflicts with other projects  #1789

**Comment by swetashre** [comment] 2019-07-29 18:36
@laszewsk - Thank you for your post. Currently we can't update to the docutils version 0.15.1 as they have only released for py2 wheel. I will mark this as a feature request pending until there is at least a py2 & py3 wheel for the docutils latest version. 

It seems like this is a duplicate of issue #1789 . I am closing this issue. Let's track the progress of this issue under the linked GitHub issue #1789.

**Closed** 2019-07-29 18:37 UTC
